// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class BestAttendancePerformer
{
    public Guid StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? TotalScheduledClasses { get; set; }

    public int? TotalAttendanceRecords { get; set; }

    public int? DaysPresent { get; set; }

    public decimal? AttendancePercentage { get; set; }
}