// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class BestAssignmentPerformer
{
    public Guid StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public decimal? AvgAssignmentGrade { get; set; }
}