// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class BestLessonPerformer
{
    public Guid? StudentID { get; set; }

    public int? CompletedLessons { get; set; }
}