// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class FeeBucket
{
    public Guid Id { get; set; }

    public Guid SchoolId { get; set; }

    public string Name { get; set; }

    public string AccountName { get; set; }

    public string AccountNumber { get; set; }

    public string BankName { get; set; }

    public bool IsMandatory { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDefault { get; set; }

    public virtual ICollection<InvoiceBucketAllocation> InvoiceBucketAllocations { get; set; } = new List<InvoiceBucketAllocation>();

    public virtual ICollection<PaymentAllocation> PaymentAllocations { get; set; } = new List<PaymentAllocation>();
}