// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class FeeStructureItem
{
    public Guid Id { get; set; }

    public Guid FeeStructureId { get; set; }

    public Guid InvoiceTypeId { get; set; }

    public decimal Amount { get; set; }

    public bool IsOptional { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? TargetType { get; set; }

    public Guid? BucketId { get; set; }

    public virtual FeeStructure FeeStructure { get; set; }

    public virtual InvoiceType InvoiceType { get; set; }
}