// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EDUSphereSharedProject.FinanceModels;

public partial class FeeStructure
{
    public Guid Id { get; set; }

    public Guid SchoolId { get; set; }

    public Guid? ClassId { get; set; }

    public string Name { get; set; }

    public DateTime TermStartDate { get; set; }

    public DateTime TermEndDate { get; set; }

    public string AcademicYear { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
  
    public virtual ICollection<FeeStructureItem> FeeStructureItems { get; set; } = new List<FeeStructureItem>();
}