// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class Invoice
{
    public Guid Id { get; set; }

    public Guid StudentFinanceId { get; set; }

    public decimal Amount { get; set; }

    public decimal PaidAmount { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime TermStartDate { get; set; }

    public DateTime TermEndDate { get; set; }

    public DateTime DueDate { get; set; }

    public DateTime IssuedDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string InvoiceType { get; set; }

    public Guid? SchoolID { get; set; }

    public string InvoiceNumber { get; set; }

    public Guid? InvoiceTypeID { get; set; }

<<<<<<< HEAD
    public bool? IsOptional { get; set; }

    public Guid? FeeStructureId { get; set; }

=======
    public bool? isOptional { get; set; }

    public Guid? FeeStructureId { get; set; }

    public virtual FeeStructure FeeStructure { get; set; }

>>>>>>> dc9665329ab527f497b3db2ffeae5ccb49613c4d
    public virtual InvoiceType InvoiceTypeNavigation { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual StudentFinance StudentFinance { get; set; }
}