// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class PaymentGatewayCredential
{
    public Guid Id { get; set; }

    public Guid PaymentGatewayAccountId { get; set; }

    public string EncryptedSecret { get; set; }

    public string KeyVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual PaymentGatewayAccount PaymentGatewayAccount { get; set; }
}