// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class PaymentGatewayAccount
{
    public Guid Id { get; set; }

    public Guid SchoolId { get; set; }

    public Guid BucketId { get; set; }

    public string Provider { get; set; }

    public string WalletId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Environment { get; set; }

    public virtual FeeBucket Bucket { get; set; }

    public virtual ICollection<PaymentGatewayCredential> PaymentGatewayCredentials { get; set; } = new List<PaymentGatewayCredential>();

    public virtual ICollection<PaymentGatewayTransaction> PaymentGatewayTransactions { get; set; } = new List<PaymentGatewayTransaction>();
}