// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class StudentFinance
{
    public Guid Id { get; set; }

    public Guid StudentId { get; set; }

    public decimal TotalFees { get; set; }

    public decimal Scholarships { get; set; }

    public decimal OutstandingAmount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid? SchoolID { get; set; }

    public virtual ICollection<FinanceLedger> FinanceLedgers { get; set; } = new List<FinanceLedger>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}