// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class Student
{
    public Guid StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? AcademicLevel { get; set; }

    public Guid? ParentID { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string StudentNumber { get; set; }

    public byte[] ProfilePic { get; set; }

    public string UserID { get; set; }

    public DateTime? DateOnBoarded { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public Guid? SchoolID { get; set; }

    public string GradeSection { get; set; }

    public string LevelName { get; set; }

    public bool? PaymentStatus { get; set; }

    public bool? isDaySchool { get; set; }

    public string GroupName { get; set; }

    public Guid? AcademicLevelID { get; set; }

    public Guid? LevelSectionID { get; set; }

    public virtual StudentFinance StudentFinance { get; set; }
}