// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class vw_ClassLessonSummary
{
    public Guid? ClassID { get; set; }

    public string ClassName { get; set; }

    public string TeacherName { get; set; }

    public byte[] ProfilePic { get; set; }

    public string Gender { get; set; }

    public Guid? SchoolID { get; set; }

    public int? TotalLessons { get; set; }

    public int? AverageRating { get; set; }
}