// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.FinanceModels;

public partial class vw_StudentLessonCompletion
{
    public int? TotalStudents { get; set; }

    public int? CurrentMonthCompletions { get; set; }

    public decimal? AvgCompletionPercentageAllTime { get; set; }

    public decimal? AvgCompletionPercentageCurrentMonth { get; set; }
}