// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EduSphereDomain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EduSphereDomain.Data
{
    public partial interface IPhoenixEdusphereContextProcedures
    {
        Task<List<CheckStudentNumberExistsResult>> CheckStudentNumberExistsAsync(string StudentNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CloseMidTermReportCardsAsync(Guid? TermSettingID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CreateBlankEndTermReportCardsAsync(Guid? TermSettingID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CreateBlankMidTermReportCardsAsync(Guid? TermSettingID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DeactivateAndCleanSchedulesResult>> DeactivateAndCleanSchedulesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GenerateStudentAttendanceResult>> GenerateStudentAttendanceAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAcademicLevelsForSchoolResult>> GetAcademicLevelsForSchoolAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetActiveClassScheduleResult>> GetActiveClassScheduleAsync(int? Grade, string SchoolID, string ClassSection, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAttendanceByTeacherAndDateResult>> GetAttendanceByTeacherAndDateAsync(string TeacherID, DateTime? AttendanceDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAttendanceSummaryResult>> GetAttendanceSummaryAsync(Guid? StudentID, DateTime? TermStartDate, DateTime? TermEndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAttendanceTrendForPastSevenDaysResult>> GetAttendanceTrendForPastSevenDaysAsync(string StudentID, string ParentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetBestPerformingStudentsBySchoolResult>> GetBestPerformingStudentsBySchoolAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetCitiesByCountryNameResult>> GetCitiesByCountryNameAsync(string CountryCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetClassLessonSummaryBySchoolResult>> GetClassLessonSummaryBySchoolAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetClinicMedicationsBySchoolResult>> GetClinicMedicationsBySchoolAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetGradedStudentAssignmentsResult>> GetGradedStudentAssignmentsAsync(Guid? StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetGradedStudentExamsResult>> GetGradedStudentExamsAsync(Guid? StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetHostelMaintainanceRequestsBySchoolResult>> GetHostelMaintainanceRequestsBySchoolAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetHostelsBySchoolResult>> GetHostelsBySchoolAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetInitializationDataResult>> GetInitializationDataAsync(string UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetLessonCountBySchoolResult>> GetLessonCountBySchoolAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetLessonsBySchoolResult>> GetLessonsBySchoolAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetLiveMeetingResult>> GetLiveMeetingAsync(string MeetingNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetMissedClassesForPastWeekResult>> GetMissedClassesForPastWeekAsync(string StudentID, string ParentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetReportCardDetailsResult>> GetReportCardDetailsAsync(Guid? ReportCardID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetReportCardsByParentResult>> GetReportCardsByParentAsync(string parentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetReportCardsByStudentResult>> GetReportCardsByStudentAsync(string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetReportCardsByTermAndStudentResult>> GetReportCardsByTermAndStudentAsync(DateTime? TermStartDate, DateTime? TermEndDate, string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetRoomsBySchoolResult>> GetRoomsBySchoolAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetSchoolDiningMenusResult>> GetSchoolDiningMenusAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetSchoolMealSessionsResult>> GetSchoolMealSessionsAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentAssignmentsResult>> GetStudentAssignmentsAsync(string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentAttendanceByUserIDAndEventDateResult>> GetStudentAttendanceByUserIDAndEventDateAsync(string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentByUserIDResult>> GetStudentByUserIDAsync(Guid? UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentClassInfoResult>> GetStudentClassInfoAsync(Guid? StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentClassScheduleResult>> GetStudentClassScheduleAsync(string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentCompletedLessonsResult>> GetStudentCompletedLessonsAsync(string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentDemographicsResult>> GetStudentDemographicsAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentDemographicsCountryResult>> GetStudentDemographicsCountryAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentExamDetailsByTeacherResult>> GetStudentExamDetailsByTeacherAsync(string UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentGrowthBySchoolResult>> GetStudentGrowthBySchoolAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentLessonsResult>> GetStudentLessonsAsync(string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentPerformanceForCurrentYearResult>> GetStudentPerformanceForCurrentYearAsync(string StudentID, string ParentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsBySchoolResult>> GetStudentsBySchoolAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsInGradeResult>> GetStudentsInGradeAsync(int? GradeLevel, string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsInGradeDetailsResult>> GetStudentsInGradeDetailsAsync(int? GradeLevel, Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsInGradeWithoutScheduleResult>> GetStudentsInGradeWithoutScheduleAsync(int? GradeLevel, string SchoolID, string ClassSection, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsInRoomResult>> GetStudentsInRoomAsync(Guid? RoomID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsWithoutRoomsByGenderResult>> GetStudentsWithoutRoomsByGenderAsync(Guid? SchoolID, Guid? GenderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsWithSpecialDietsResult>> GetStudentsWithSpecialDietsAsync(Guid? SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentUnCompletedLessonsResult>> GetStudentUnCompletedLessonsAsync(string StudentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTeacherAssignmentsResult>> GetTeacherAssignmentsAsync(string TeacherID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTeacherLessonsResult>> GetTeacherLessonsAsync(string TeacherID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTeacherSubjectByTeacherIDResult>> GetTeacherSubjectByTeacherIDAsync(Guid? TeacherID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTop5TeachersByHighRatedLessonsResult>> GetTop5TeachersByHighRatedLessonsAsync(string SchoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetUpcomingExamsOrQuizzesResult>> GetUpcomingExamsOrQuizzesAsync(int? StudentGrade, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetUserBadgesByUserIDResult>> GetUserBadgesByUserIDAsync(string UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RunDailyJobsResult>> RunDailyJobsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SyncStudentAndParentAccountStatusAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SyncStudentsToClassesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateEndTermReportCardStatusAsync(Guid? TermSettingID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetStaffBySchoolAndRoleResult>> usp_GetStaffBySchoolAndRoleAsync(Guid? SchoolID, string RoleName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
