// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EduSphereDomain.Models;
using EDUSphereSharedProject.Models;
using Microsoft.EntityFrameworkCore;

namespace EduSphereDomain.Data;

public partial class PhoenixEdusphereContext : DbContext
{
    public PhoenixEdusphereContext(DbContextOptions<PhoenixEdusphereContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<AssignmentQuestion> AssignmentQuestions { get; set; }

    public virtual DbSet<Attendance> Attendances { get; set; }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<ClassSchedule> ClassSchedules { get; set; }

    public virtual DbSet<ClientAdmin> ClientAdmins { get; set; }

    public virtual DbSet<DayofTheWeek> DayofTheWeeks { get; set; }

    public virtual DbSet<ExamQuizTestHeader> ExamQuizTestHeaders { get; set; }

    public virtual DbSet<ExamQuizTestQuestion> ExamQuizTestQuestions { get; set; }

    public virtual DbSet<Gender> Genders { get; set; }

    public virtual DbSet<Grade> Grades { get; set; }

    public virtual DbSet<GradingScale> GradingScales { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Parent> Parents { get; set; }

    public virtual DbSet<ReportCard> ReportCards { get; set; }

    public virtual DbSet<ReportCardDetail> ReportCardDetails { get; set; }

    public virtual DbSet<School> Schools { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentAssignment> StudentAssignments { get; set; }

    public virtual DbSet<StudentAssignmentAnswer> StudentAssignmentAnswers { get; set; }

    public virtual DbSet<StudentAttendance> StudentAttendances { get; set; }

    public virtual DbSet<StudentClass> StudentClasses { get; set; }

    public virtual DbSet<StudentClassSchedule> StudentClassSchedules { get; set; }

    public virtual DbSet<StudentCompletedLesson> StudentCompletedLessons { get; set; }

    public virtual DbSet<StudentExamQuizAndTestAnswer> StudentExamQuizAndTestAnswers { get; set; }

    public virtual DbSet<StudentExamsTestsAndQuiz> StudentExamsTestsAndQuizzes { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    public virtual DbSet<TeacherSubjectNormalized> TeacherSubjectNormalizeds { get; set; }

    public virtual DbSet<TimeSlot> TimeSlots { get; set; }

    public virtual DbSet<WorldCity> WorldCities { get; set; }

    public virtual DbSet<vw_AllLesson> vw_AllLessons { get; set; }

    public virtual DbSet<vw_ClassLessonSummary> vw_ClassLessonSummaries { get; set; }

    public virtual DbSet<vw_ClassTeacherDetail> vw_ClassTeacherDetails { get; set; }

    public virtual DbSet<vw_CompletedLessonsPerStudent> vw_CompletedLessonsPerStudents { get; set; }

    public virtual DbSet<vw_HighRatedLesson> vw_HighRatedLessons { get; set; }

    public virtual DbSet<vw_LowRatedClassSummary> vw_LowRatedClassSummaries { get; set; }

    public virtual DbSet<vw_PerformantTeacherSubject> vw_PerformantTeacherSubjects { get; set; }

    public virtual DbSet<vw_StudentAttendanceSummary> vw_StudentAttendanceSummaries { get; set; }

    public virtual DbSet<vw_StudentClassSchedule> vw_StudentClassSchedules { get; set; }

    public virtual DbSet<vw_StudentGrowth> vw_StudentGrowths { get; set; }

    public virtual DbSet<vw_StudentLessonCompletion> vw_StudentLessonCompletions { get; set; }

    public virtual DbSet<vw_StudentPerformance> vw_StudentPerformances { get; set; }

    public virtual DbSet<vw_TopPerformingTeacher> vw_TopPerformingTeachers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.AccountActive)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);
            entity.Property(e => e.requiresPasswordReset)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentID).HasName("PK__Assignme__32499E57F051FB73");

            entity.Property(e => e.AssignmentID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.DueDate).HasColumnType("date");
            entity.Property(e => e.Title).HasMaxLength(100);

            entity.HasOne(d => d.Class).WithMany(p => p.Assignments)
                .HasForeignKey(d => d.ClassID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Assignmen__Class__38996AB5");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Assignments)
                .HasForeignKey(d => d.TeacherID)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Assignmen__Teach__398D8EEE");
        });

        modelBuilder.Entity<AssignmentQuestion>(entity =>
        {
            entity.HasKey(e => e.QuestionID).HasName("PK__Assignme__0DC06F8C5215A51C");

            entity.Property(e => e.QuestionID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.QuestionText).IsRequired();

            entity.HasOne(d => d.Assignment).WithMany(p => p.AssignmentQuestions)
                .HasForeignKey(d => d.AssignmentID)
                .HasConstraintName("FK_Assignment_AssignmentQuestions");
        });

        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.HasKey(e => e.AttendanceID).HasName("PK__Attendan__8B69263C6C6C243B");

            entity.ToTable("Attendance");

            entity.Property(e => e.AttendanceID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.AttendanceDate).HasColumnType("date");
            entity.Property(e => e.Status).HasMaxLength(10);

            entity.HasOne(d => d.Class).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.ClassID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Attendanc__Class__49C3F6B7");

            entity.HasOne(d => d.Student).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_Attendance_Students");
        });

        modelBuilder.Entity<Class>(entity =>
        {
            entity.HasKey(e => e.ClassID).HasName("PK__Classes__CB1927A06DD025F1");

            entity.Property(e => e.ClassID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ClassName).HasMaxLength(50);
            entity.Property(e => e.GradeSection).HasMaxLength(50);

            entity.HasOne(d => d.SChool).WithMany(p => p.Classes)
                .HasForeignKey(d => d.SChoolID)
                .HasConstraintName("FK_Classes_Schools");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Classes)
                .HasForeignKey(d => d.TeacherID)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Classes__Teacher__300424B4");
        });

        modelBuilder.Entity<ClassSchedule>(entity =>
        {
            entity.ToTable("ClassSchedule");

            entity.Property(e => e.ClassScheduleID).ValueGeneratedNever();
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Class).WithMany(p => p.ClassSchedules)
                .HasForeignKey(d => d.ClassID)
                .HasConstraintName("FK_ClassSchedule_Classes");

            entity.HasOne(d => d.DayOfTheWeek).WithMany(p => p.ClassSchedules)
                .HasForeignKey(d => d.DayOfTheWeekID)
                .HasConstraintName("FK_ClassSchedule_DayofTheWeek");

            entity.HasOne(d => d.TimeSlot).WithMany(p => p.ClassSchedules)
                .HasForeignKey(d => d.TimeSlotID)
                .HasConstraintName("FK_ClassSchedule_TimeSlots");
        });

        modelBuilder.Entity<ClientAdmin>(entity =>
        {
            entity.HasKey(e => e.AdminID);

            entity.Property(e => e.AdminID).ValueGeneratedNever();
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MobileNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Nationality)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.School).WithMany(p => p.ClientAdmins)
                .HasForeignKey(d => d.SchoolID)
                .HasConstraintName("FK_ClientAdmins_Schools");
        });

        modelBuilder.Entity<DayofTheWeek>(entity =>
        {
            entity.HasKey(e => e.DayID);

            entity.ToTable("DayofTheWeek");

            entity.Property(e => e.DayID).ValueGeneratedNever();
            entity.Property(e => e.DayName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ExamQuizTestHeader>(entity =>
        {
            entity.HasKey(e => e.ExamQuizID).HasName("PK__ExamQuiz__97624184692F23EF");

            entity.ToTable("ExamQuizTestHeader");

            entity.Property(e => e.ExamQuizID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.ExamType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Class).WithMany(p => p.ExamQuizTestHeaders)
                .HasForeignKey(d => d.ClassID)
                .HasConstraintName("FK_ExamQuizTestHeader_Classes");

            entity.HasOne(d => d.Teacher).WithMany(p => p.ExamQuizTestHeaders)
                .HasForeignKey(d => d.TeacherID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExamQuizHeader_Teachers");
        });

        modelBuilder.Entity<ExamQuizTestQuestion>(entity =>
        {
            entity.HasKey(e => e.QuestionID).HasName("PK__ExamQuiz__0DC06F8CB6D15C33");

            entity.Property(e => e.QuestionID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.QuestionText).IsRequired();
            entity.Property(e => e.QuestionType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.ExamQuiz).WithMany(p => p.ExamQuizTestQuestions)
                .HasForeignKey(d => d.ExamQuizID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExamQuizQuestions_ExamQuizTestHeader");
        });

        modelBuilder.Entity<Gender>(entity =>
        {
            entity.ToTable("Gender");

            entity.Property(e => e.GenderId).ValueGeneratedNever();
            entity.Property(e => e.GenderDescription).HasMaxLength(50);
        });

        modelBuilder.Entity<Grade>(entity =>
        {
            entity.HasKey(e => e.GradeID).HasName("PK__Grades__54F87A37F98FBE7C");

            entity.Property(e => e.GradeID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.DateAssigned)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.Grade1)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("Grade");

            entity.HasOne(d => d.Assignment).WithMany(p => p.Grades)
                .HasForeignKey(d => d.AssignmentID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Grades__Assignme__5441852A");

            entity.HasOne(d => d.Student).WithMany(p => p.Grades)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_Grades_Students");
        });

        modelBuilder.Entity<GradingScale>(entity =>
        {
            entity.ToTable("GradingScale");

            entity.Property(e => e.GradingScaleID).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.GPA).HasColumnType("decimal(3, 2)");
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.LessonID).HasName("PK__Lessons__B084ACB08BA07F8D");

            entity.Property(e => e.LessonID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.DatePosted)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.Title).HasMaxLength(100);

            entity.HasOne(d => d.Class).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.ClassID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Lessons__ClassID__4316F928");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.TeacherID)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Lessons__Teacher__440B1D61");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationID).HasName("PK__Notifica__20CF2E326E3E86A6");

            entity.Property(e => e.NotificationID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.DateSent)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsRead).HasDefaultValueSql("((0))");
            entity.Property(e => e.Message).HasMaxLength(250);
        });

        modelBuilder.Entity<Parent>(entity =>
        {
            entity.HasKey(e => e.ParentID).HasName("PK__Parents__D339510FA190A9DA");

            entity.Property(e => e.ParentID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.City).IsUnicode(false);
            entity.Property(e => e.Country).IsUnicode(false);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasMaxLength(450);

            entity.HasOne(d => d.School).WithMany(p => p.Parents)
                .HasForeignKey(d => d.SchoolID)
                .HasConstraintName("FK_Parents_Schools");
        });

        modelBuilder.Entity<ReportCard>(entity =>
        {
            entity.HasKey(e => e.ReportCardID).HasName("PK__ReportCa__CBAAABBCD81269AE");

            entity.Property(e => e.ReportCardID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.GPA).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.GradeSection).HasMaxLength(50);
            entity.Property(e => e.IssuedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.Term).HasMaxLength(20);
            entity.Property(e => e.TermEndDate).HasColumnType("datetime");
            entity.Property(e => e.TermStartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Student).WithMany(p => p.ReportCards)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_ReportCards_Students");
        });

        modelBuilder.Entity<ReportCardDetail>(entity =>
        {
            entity.Property(e => e.ReportCardDetailID).ValueGeneratedNever();
            entity.Property(e => e.Grade)
                .HasMaxLength(10)
                .IsFixedLength();

            entity.HasOne(d => d.Class).WithMany(p => p.ReportCardDetails)
                .HasForeignKey(d => d.ClassID)
                .HasConstraintName("FK_ReportCardDetails_Classes");

            entity.HasOne(d => d.ReportCard).WithMany(p => p.ReportCardDetails)
                .HasForeignKey(d => d.ReportCardID)
                .HasConstraintName("FK_ReportCardDetails_ReportCards");
        });

        modelBuilder.Entity<School>(entity =>
        {
            entity.Property(e => e.SchoolID).ValueGeneratedNever();
            entity.Property(e => e.SchoolName).IsUnicode(false);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentID).HasName("PK__Students__32C52A7994DE34D7");

            entity.Property(e => e.StudentID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DateOnBoarded).HasColumnType("datetime");
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.Gender).HasMaxLength(10);
            entity.Property(e => e.GradeSection).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.StudentNumber)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Parent).WithMany(p => p.Students)
                .HasForeignKey(d => d.ParentID)
                .HasConstraintName("FK_Students_Parents");
        });

        modelBuilder.Entity<StudentAssignment>(entity =>
        {
            entity.HasKey(e => e.StudentAssignmentID).HasName("PK__StudentA__1DDF88DBBD757185");

            entity.Property(e => e.StudentAssignmentID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Grade).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.SubmissionDate).HasColumnType("date");

            entity.HasOne(d => d.Assignment).WithMany(p => p.StudentAssignments)
                .HasForeignKey(d => d.AssignmentID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__StudentAs__Assig__3E52440B");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentAssignments)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_StudentAssignments_Students");
        });

        modelBuilder.Entity<StudentAssignmentAnswer>(entity =>
        {
            entity.HasKey(e => e.AnswerID).HasName("PK__StudentA__D4825024806FF9A3");

            entity.Property(e => e.AnswerID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.AnsweredDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Question).WithMany(p => p.StudentAssignmentAnswers)
                .HasForeignKey(d => d.QuestionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentAssignmentAnswers_AssignmentQuestions");

            entity.HasOne(d => d.StudentAssignment).WithMany(p => p.StudentAssignmentAnswers)
                .HasForeignKey(d => d.StudentAssignmentID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentAssignment_StudentAssignmentAnswers");
        });

        modelBuilder.Entity<StudentAttendance>(entity =>
        {
            entity.ToTable("StudentAttendance");

            entity.Property(e => e.StudentAttendanceID).ValueGeneratedNever();
            entity.Property(e => e.AttendanceDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<StudentClass>(entity =>
        {
            entity.HasKey(e => e.StudentClassID).HasName("PK__StudentC__2FF1216750223F72");

            entity.Property(e => e.StudentClassID).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Class).WithMany(p => p.StudentClasses)
                .HasForeignKey(d => d.ClassID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__StudentCl__Class__34C8D9D1");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentClasses)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_StudentClasses_Students");
        });

        modelBuilder.Entity<StudentClassSchedule>(entity =>
        {
            entity.Property(e => e.StudentClassScheduleID).ValueGeneratedNever();

            entity.HasOne(d => d.Schedule).WithMany(p => p.StudentClassSchedules)
                .HasForeignKey(d => d.ScheduleID)
                .HasConstraintName("FK_StudentClassSchedules_ClassSchedule1");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentClassSchedules)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_StudentClassSchedules_Students");
        });

        modelBuilder.Entity<StudentCompletedLesson>(entity =>
        {
            entity.HasKey(e => e.StudentLessonCompletionID);

            entity.Property(e => e.StudentLessonCompletionID).ValueGeneratedNever();
            entity.Property(e => e.CompletionDate).HasColumnType("datetime");

            entity.HasOne(d => d.Lesson).WithMany(p => p.StudentCompletedLessons)
                .HasForeignKey(d => d.LessonID)
                .HasConstraintName("FK_StudentCompletedLessons_Lessons");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentCompletedLessons)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_StudentCompletedLessons_Students");
        });

        modelBuilder.Entity<StudentExamQuizAndTestAnswer>(entity =>
        {
            entity.HasKey(e => e.StudentExamAnswerID);

            entity.Property(e => e.StudentExamAnswerID).ValueGeneratedNever();
            entity.Property(e => e.AnswerDate).HasColumnType("datetime");

            entity.HasOne(d => d.Header).WithMany(p => p.StudentExamQuizAndTestAnswers)
                .HasForeignKey(d => d.HeaderID)
                .HasConstraintName("FK_StudentExamQuizAndTestAnswers_StudentExamsTestsAndQuizzes");

            entity.HasOne(d => d.Question).WithMany(p => p.StudentExamQuizAndTestAnswers)
                .HasForeignKey(d => d.QuestionID)
                .HasConstraintName("FK_StudentExamQuizAndTestAnswers_ExamQuizTestQuestions");
        });

        modelBuilder.Entity<StudentExamsTestsAndQuiz>(entity =>
        {
            entity.HasKey(e => e.StudentExamID);

            entity.Property(e => e.StudentExamID).ValueGeneratedNever();
            entity.Property(e => e.Grade).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.SubmissionDate).HasColumnType("datetime");

            entity.HasOne(d => d.Exam).WithMany(p => p.StudentExamsTestsAndQuizzes)
                .HasForeignKey(d => d.ExamID)
                .HasConstraintName("FK_StudentExamsTestsAndQuizzes_ExamQuizTestHeader");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentExamsTestsAndQuizzes)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_StudentExamsTestsAndQuizzes_Students");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.ToTable("Subject");

            entity.Property(e => e.SubjectID).ValueGeneratedNever();
            entity.Property(e => e.SubjectName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.HasKey(e => e.TeacherID).HasName("PK__Teachers__EDF259444628D1F1");

            entity.Property(e => e.TeacherID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ContactNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DateEngaged).HasColumnType("datetime");
            entity.Property(e => e.DateTerminated).HasColumnType("datetime");
            entity.Property(e => e.EmailAddress).IsUnicode(false);
            entity.Property(e => e.EmployeeID)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.Nationality)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.School).WithMany(p => p.Teachers)
                .HasForeignKey(d => d.SchoolID)
                .HasConstraintName("FK_Teachers_Schools");
        });

        modelBuilder.Entity<TeacherSubjectNormalized>(entity =>
        {
            entity.HasKey(e => e.TeacherSubjectID);

            entity.ToTable("TeacherSubjectNormalized");

            entity.Property(e => e.TeacherSubjectID).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Subject).WithMany(p => p.TeacherSubjectNormalizeds)
                .HasForeignKey(d => d.SubjectID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeacherSubjectNormalized_Subject");

            entity.HasOne(d => d.Teacher).WithMany(p => p.TeacherSubjectNormalizeds)
                .HasForeignKey(d => d.TeacherID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeacherSubjectNormalized_Teacher");
        });

        modelBuilder.Entity<TimeSlot>(entity =>
        {
            entity.Property(e => e.TimeslotID).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WorldCity>(entity =>
        {
            entity.HasKey(e => e.CityID);

            entity.Property(e => e.CityID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CityName).IsUnicode(false);
            entity.Property(e => e.CountryCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CountryName).IsUnicode(false);
        });

        modelBuilder.Entity<vw_AllLesson>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_AllLessons");

            entity.Property(e => e.DatePosted).HasColumnType("date");
            entity.Property(e => e.Title).HasMaxLength(100);
        });

        modelBuilder.Entity<vw_ClassLessonSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_ClassLessonSummary");

            entity.Property(e => e.ClassName).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TeacherName).HasMaxLength(101);
        });

        modelBuilder.Entity<vw_ClassTeacherDetail>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_ClassTeacherDetails");

            entity.Property(e => e.ClassName).HasMaxLength(50);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName).HasMaxLength(50);
        });

        modelBuilder.Entity<vw_CompletedLessonsPerStudent>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_CompletedLessonsPerStudent");

            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.StudentNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<vw_HighRatedLesson>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_HighRatedLessons");

            entity.Property(e => e.DatePosted).HasColumnType("date");
            entity.Property(e => e.Title).HasMaxLength(100);
        });

        modelBuilder.Entity<vw_LowRatedClassSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_LowRatedClassSummary");

            entity.Property(e => e.ClassName).HasMaxLength(50);
            entity.Property(e => e.TeacherName).HasMaxLength(101);
        });

        modelBuilder.Entity<vw_PerformantTeacherSubject>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_PerformantTeacherSubject");

            entity.Property(e => e.SubjectName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TeacherName).HasMaxLength(101);
        });

        modelBuilder.Entity<vw_StudentAttendanceSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_StudentAttendanceSummary");

            entity.Property(e => e.DayName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.GPA).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.IssuedDate).HasColumnType("date");
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.Term).HasMaxLength(20);
            entity.Property(e => e.TermEndDate).HasColumnType("datetime");
            entity.Property(e => e.TermStartDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<vw_StudentClassSchedule>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_StudentClassSchedule");

            entity.Property(e => e.ClassName).HasMaxLength(50);
            entity.Property(e => e.DayName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<vw_StudentGrowth>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_StudentGrowth");

            entity.Property(e => e.PercentageIncreaseInStudents).HasColumnType("numeric(26, 12)");
        });

        modelBuilder.Entity<vw_StudentLessonCompletion>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_StudentLessonCompletion");

            entity.Property(e => e.AvgCompletionPercentageAllTime).HasColumnType("numeric(26, 12)");
            entity.Property(e => e.AvgCompletionPercentageCurrentMonth).HasColumnType("numeric(26, 12)");
        });

        modelBuilder.Entity<vw_StudentPerformance>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_StudentPerformance");

            entity.Property(e => e.AverageMonthlyScore).HasColumnType("numeric(38, 6)");
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.PreviousAverage).HasColumnType("numeric(38, 6)");
        });

        modelBuilder.Entity<vw_TopPerformingTeacher>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TopPerformingTeachers");

            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}