// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.AchievementModels;

public partial class Activity
{
    public Guid ActivityID { get; set; }

    public string Activity1 { get; set; }

    public string ActivityDescription { get; set; }

    public string ActivityType { get; set; }

    public int? Points { get; set; }

    public virtual ICollection<UserActivity> UserActivities { get; set; } = new List<UserActivity>();
}