// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EduSphereDomain.Models;
using EDUSphereSharedProject.AchievementModels;
using Microsoft.EntityFrameworkCore;

namespace EduSphereDomain.AchievementsData;

public partial class AchivementContext : DbContext
{
    public AchivementContext(DbContextOptions<AchivementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<Badge> Badges { get; set; }

    public virtual DbSet<UserActivity> UserActivities { get; set; }

    public virtual DbSet<UserBadge> UserBadges { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Activity>(entity =>
        {
            entity.Property(e => e.ActivityID).ValueGeneratedNever();
            entity.Property(e => e.Activity1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Activity");
            entity.Property(e => e.ActivityDescription).HasColumnType("text");
            entity.Property(e => e.ActivityType)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Badge>(entity =>
        {
            entity.Property(e => e.BadgeId).ValueGeneratedNever();
            entity.Property(e => e.BadgeDescription).HasColumnType("text");
            entity.Property(e => e.BadgeName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.image_url).IsUnicode(false);
        });

        modelBuilder.Entity<UserActivity>(entity =>
        {
            entity.HasKey(e => e.ActivityId);

            entity.Property(e => e.ActivityId).ValueGeneratedNever();
            entity.Property(e => e.ActivityDate).HasColumnType("datetime");
            entity.Property(e => e.Score).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.UserId).HasMaxLength(255);

            entity.HasOne(d => d.RelatedActivityNavigation).WithMany(p => p.UserActivities)
                .HasForeignKey(d => d.RelatedActivity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserActivities_Activities");
        });

        modelBuilder.Entity<UserBadge>(entity =>
        {
            entity.Property(e => e.UserBadgeID).ValueGeneratedNever();
            entity.Property(e => e.DateEarned).HasColumnType("datetime");

            entity.HasOne(d => d.Badge).WithMany(p => p.UserBadges)
                .HasForeignKey(d => d.BadgeID)
                .HasConstraintName("FK_UserBadges_Badges");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}