// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetActiveClassScheduleResult
    {
        public Guid ClassScheduleID { get; set; }
        public Guid? ClassID { get; set; }
        public Guid? TimeSlotID { get; set; }
        public Guid? DayOfTheWeekID { get; set; }
        [StringLength(50)]
        public string DayName { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        [StringLength(50)]
        public string ClassName { get; set; }
        public int? AcademicLevel { get; set; }
    }
}
