// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetAcademicLevelsForSchoolResult
    {
        public Guid AcademicLevelID { get; set; }
        public int? LevelInt { get; set; }
        public string LevelName { get; set; }
        public string GroupName { get; set; }
    }
}
