// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetAttendanceTrendForPastSevenDaysResult
    {
        public Guid? StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Column(TypeName = "decimal(26,12)")]
        public decimal? AttendancePercentage { get; set; }
        public int? TotalClasses { get; set; }
        public int? TotalPresent { get; set; }
        public int? TotalAbsent { get; set; }
    }
}
