// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetBestPerformingStudentsBySchoolResult
    {
        public Guid StudentID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        public Guid? SchoolID { get; set; }
        public byte[] ProfilePic { get; set; }
        [Column("AvgExamGrade", TypeName = "decimal(38,6)")]
        public decimal? AvgExamGrade { get; set; }
        [Column("AvgAssignmentGrade", TypeName = "decimal(38,6)")]
        public decimal? AvgAssignmentGrade { get; set; }
        [Column("MarksScore", TypeName = "decimal(38,6)")]
        public decimal? MarksScore { get; set; }
        [Column("AttendanceScore", TypeName = "decimal(26,12)")]
        public decimal? AttendanceScore { get; set; }
        public int? LessonScore { get; set; }
        public int? BadgeScore { get; set; }
        [Column("FinalScore", TypeName = "decimal(38,6)")]
        public decimal? FinalScore { get; set; }
    }
}
