// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetConsolidatedEndTermReportResult
    {
        public Guid StudentID { get; set; }
        [StringLength(101)]
        public string StudentName { get; set; }
        [StringLength(20)]
        public string Term { get; set; }
        public DateTime? IssuedDate { get; set; }
        [StringLength(50)]
        public string Grade { get; set; }
        [StringLength(50)]
        public string GradeSection { get; set; }
        public int? Points { get; set; }
        public int? PointsInBestSix { get; set; }
        public int? PositionInClass { get; set; }
        public bool IsGCE { get; set; }
        [StringLength(3)]
        public string PointsDisplay { get; set; }
        [StringLength(3)]
        public string PositionDisplay { get; set; }
        [StringLength(4000)]
        public string SubjectList { get; set; }
    }
}
