// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetClinicVisitsWithMedicationLogsResult
    {
        public Guid VisitId { get; set; }
        public Guid ClinicId { get; set; }
        public Guid StudentId { get; set; }
        public DateTime VisitDate { get; set; }
        public string Symptoms { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string Notes { get; set; }
        public Guid? AttendedByStaffId { get; set; }
        public int? DaysOff { get; set; }
        public DateTime? ReturnToClassDate { get; set; }
        public bool? IsActive { get; set; }
        public Guid? LogId { get; set; }
        public Guid? MedicationId { get; set; }
        public int? QuantityUsed { get; set; }
    }
}
