// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetCitiesByCountryNameResult
    {
        public Guid CityID { get; set; }
        [StringLength(2147483647)]
        public string CityName { get; set; }
        [StringLength(2147483647)]
        public string CountryName { get; set; }
        [StringLength(50)]
        public string CountryCode { get; set; }
    }
}
