// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetClinicStaffBySchoolResult
    {
        public Guid StaffId { get; set; }
        public Guid ClinicId { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
        public string Contact { get; set; }
        public string UserID { get; set; }
        public string EmployeeID { get; set; }
    }
}
