// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetGradedStudentAssignmentsResult
    {
        public Guid StudentAssignmentID { get; set; }
        public Guid? StudentID { get; set; }
        public Guid? AssignmentID { get; set; }
        public DateTime? SubmissionDate { get; set; }
        [Column("Grade", TypeName = "decimal(5,2)")]
        public decimal? Grade { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        public Guid? QuestionID { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        public int? AssignmentTotalMarks { get; set; }
        [StringLength(50)]
        public string TeacherFirstName { get; set; }
        [StringLength(50)]
        public string TeacherLastName { get; set; }
    }
}
