// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetGradedStudentExamsResult
    {
        [StringLength(50)]
        public string TeacherFirstName { get; set; }
        [StringLength(50)]
        public string TeacherLastName { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        public int TotalMarks { get; set; }
        public Guid StudentExamID { get; set; }
        public Guid? StudentID { get; set; }
        [Column("Grade", TypeName = "decimal(5,2)")]
        public decimal? Grade { get; set; }
        public Guid? ExamID { get; set; }
        public DateTime? SubmissionDate { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
    }
}
