// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetInventoryBatchesBySchoolResult
    {
        public Guid BatchID { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public bool HasFixedExpiry { get; set; }
        public int? DefaultShelfLife { get; set; }
        public string Category { get; set; }
        public Guid FoodItemID { get; set; }
        [Column(TypeName = "decimal(10,2)")]
        public decimal Quantity { get; set; }
        public DateTime ReceivedDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string StorageLocation { get; set; }
        [Column(TypeName = "decimal(5,2)")]
        public decimal? CurrentTemp { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public bool AIAdviceGenerated { get; set; }
    }
}
