// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetInventoryBatchesBySchoolResult
    {
        public Guid BatchID { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        [StringLength(20)]
        public string Unit { get; set; }
        public bool HasFixedExpiry { get; set; }
        public int? DefaultShelfLife { get; set; }
        [StringLength(50)]
        public string Category { get; set; }
        public Guid FoodItemID { get; set; }
        [Column("Quantity", TypeName = "decimal(10,2)")]
        public decimal Quantity { get; set; }
        public DateTime ReceivedDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        [StringLength(50)]
        public string StorageLocation { get; set; }
        [Column("CurrentTemp", TypeName = "decimal(5,2)")]
        public decimal? CurrentTemp { get; set; }
        [StringLength(8)]
        public string Status { get; set; }
        [StringLength(2147483647)]
        public string Notes { get; set; }
        public bool AIAdviceGenerated { get; set; }
    }
}
