// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetLiveMeetingResult
    {
        public Guid MeetingID { get; set; }
        [StringLength(50)]
        public string MeetingNumber { get; set; }
        [StringLength(50)]
        public string MeetingPassword { get; set; }
        public Guid? CreatedBy { get; set; }
        [StringLength(255)]
        public string CreatorEmail { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ScheduledDate { get; set; }
        public bool? isDone { get; set; }
    }
}
