// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetLessonsBySchoolResult
    {
        public Guid LessonID { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        [StringLength(2147483647)]
        public string Content { get; set; }
        public Guid? ClassID { get; set; }
        public Guid? TeacherID { get; set; }
        public DateTime? DatePosted { get; set; }
        public int? Rating { get; set; }
        public int? NumberOfRatings { get; set; }
        public Guid? SchoolID { get; set; }
    }
}
