// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetReportCardDetailsResult
    {
        public Guid ReportCardDetailID { get; set; }
        public Guid? ReportCardID { get; set; }
        [StringLength(50)]
        public string ClassName { get; set; }
        public double? Score { get; set; }
        public string Grade { get; set; }
        public Guid? ClassID { get; set; }
        [StringLength(50)]
        public string Final { get; set; }
    }
}
