// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetReportCardsByTermAndStudentResult
    {
        public Guid ReportCardID { get; set; }
        public Guid? StudentID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        public int? AcademicLevel { get; set; }
        [StringLength(50)]
        public string LevelName { get; set; }
        [StringLength(20)]
        public string Term { get; set; }
        [Column("GPA", TypeName = "decimal(4,2)")]
        public decimal? GPA { get; set; }
        public DateTime? IssuedDate { get; set; }
        public DateTime? TermStartDate { get; set; }
        public DateTime? TermEndDate { get; set; }
    }
}
