// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetRoomsBySchoolResult
    {
        public Guid RoomId { get; set; }
        public Guid HostelId { get; set; }
        [StringLength(20)]
        public string RoomNumber { get; set; }
        public int MaxOccupancy { get; set; }
        [StringLength(50)]
        public string RoomType { get; set; }
        [StringLength(100)]
        public string HostelName { get; set; }
        public Guid? GenderId { get; set; }
        [StringLength(50)]
        public string GenderDescription { get; set; }
        public int? OccupiedCount { get; set; }
        public bool? IsFull { get; set; }
    }
}
