// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentAssignmentsResult
    {
        public Guid AssignmentID { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        [StringLength(2147483647)]
        public string Description { get; set; }
        public DateTime? DueDate { get; set; }
        public Guid? ClassID { get; set; }
        public Guid? TeacherID { get; set; }
        public int? TotalMarks { get; set; }
        [StringLength(50)]
        public string ClassName { get; set; }
        public Guid StudentID { get; set; }
        public int Overdue { get; set; }
    }
}
