// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetSchoolDiningMenusResult
    {
        public Guid MenuId { get; set; }
        public Guid MealId { get; set; }
        [StringLength(10)]
        public string DayOfWeek { get; set; }
        [StringLength(100)]
        public string MainDish { get; set; }
        [StringLength(100)]
        public string SideDish { get; set; }
        [StringLength(100)]
        public string Drink { get; set; }
        [StringLength(50)]
        public string MealName { get; set; }
    }
}
