// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentFinanceBySchoolResult
    {
        public Guid Id { get; set; }
        public Guid StudentId { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalFees { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal Scholarships { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal OutstandingAmount { get; set; }
        public string Status { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}
