// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentsBySchoolResult
    {
        public Guid StudentID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        public int? AcademicLevel { get; set; }
        public Guid? ParentID { get; set; }
        [StringLength(10)]
        public string Gender { get; set; }
        [StringLength(2147483647)]
        public string Address { get; set; }
        [StringLength(50)]
        public string StudentNumber { get; set; }
        public byte[] ProfilePic { get; set; }
        [StringLength(2147483647)]
        public string UserID { get; set; }
        public DateTime? DateOnBoarded { get; set; }
        [StringLength(50)]
        public string Country { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        public Guid? SchoolID { get; set; }
        [StringLength(50)]
        public string GradeSection { get; set; }
        [StringLength(50)]
        public string LevelName { get; set; }
    }
}
