// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentsWithSpecialDietsResult
    {
        public Guid DietId { get; set; }
        public Guid StudentId { get; set; }
        [StringLength(50)]
        public string DietType { get; set; }
        [StringLength(255)]
        public string Description { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(10)]
        public string Gender { get; set; }
        public byte[] ProfilePic { get; set; }
        [StringLength(50)]
        public string StudentNumber { get; set; }
        [StringLength(50)]
        public string AcademicLevel { get; set; }
    }
}
