// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentDemographicsResult
    {
        public string Country { get; set; }
        public string City { get; set; }
        public int? StudentCount { get; set; }
    }
}
