// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentGrowthBySchoolResult
    {
        public Guid? SchoolID { get; set; }
        public int? TotalStudents { get; set; }
        public int? NewStudentsCurrentMonth { get; set; }
        [Column("PercentageIncreaseInStudents", TypeName = "decimal(26,12)")]
        public decimal? PercentageIncreaseInStudents { get; set; }
    }
}
