// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentAttendanceByUserIDAndEventDateResult
    {
        public Guid StudentAttendanceID { get; set; }
        public DateTime? AttendanceDate { get; set; }
        public string ClassName { get; set; }
        public Guid? StudentScheduleID { get; set; }
        public bool? LateStatus { get; set; }
        public bool? AttendanceStatus { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int Marked { get; set; }
    }
}
