// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentInvoicesResult
    {
        public Guid Id { get; set; }
        public Guid StudentFinanceId { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }
        [Column("PaidAmount", TypeName = "decimal(18,2)")]
        public decimal PaidAmount { get; set; }
        [StringLength(50)]
        public string PaymentStatus { get; set; }
        public DateTime TermStartDate { get; set; }
        public DateTime TermEndDate { get; set; }
        public DateTime DueDate { get; set; }
        public DateTime IssuedDate { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        [StringLength(50)]
        public string InvoiceType { get; set; }
        public Guid? InvoiceTypeID { get; set; }
        public Guid? SchoolID { get; set; }
        [StringLength(89)]
        public string TermLabel { get; set; }
        public int StatusOrder { get; set; }
    }
}
