// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetStudentPerformanceForCurrentYearResult
    {
        public Guid? StudentID { get; set; }
        [StringLength(2147483647)]
        public string UserID { get; set; }
        public Guid? ParentID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        public int? Year { get; set; }
        [StringLength(30)]
        public string MonthName { get; set; }
        [Column("AverageMonthlyScore", TypeName = "decimal(38,6)")]
        public decimal? AverageMonthlyScore { get; set; }
        [Column("PreviousAverage", TypeName = "decimal(38,6)")]
        public decimal PreviousAverage { get; set; }
        public int IsImproving { get; set; }
    }
}
