// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetTeacherAssignmentsResult
    {
        public Guid StudentAssignmentID { get; set; }
        public Guid? StudentID { get; set; }
        public Guid? AssignmentID { get; set; }
        public DateTime? SubmissionDate { get; set; }
        [Column("Grade", TypeName = "decimal(5,2)")]
        public decimal? Grade { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        public Guid? QuestionID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        public int? TotalMarks { get; set; }
        [StringLength(50)]
        public string ClassName { get; set; }
        public int? GradeLevel { get; set; }
        public int Overdue { get; set; }
    }
}
