// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetTimetableOverridesBySchoolResult
    {
        public Guid TimetableOverrideID { get; set; }
        public int AcademicLevel { get; set; }
        public string GradeSection { get; set; }
        public string StudentGroup { get; set; }
        public Guid DayOfTheWeekID { get; set; }
        public Guid TimeSlotID { get; set; }
        public Guid ReplacementClassID { get; set; }
        public string Reason { get; set; }
        public bool IsActive { get; set; }
        public DateTime? EffectiveFrom { get; set; }
        public DateTime? EffectiveTo { get; set; }
        public DateTime CreatedAt { get; set; }
        public Guid? CreatedBy { get; set; }
    }
}
