// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetTop5TeachersByHighRatedLessonsResult
    {
        public Guid TeacherID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        public byte[] ProfilePic { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        public int? AverageRating { get; set; }
        public int? TotalHighRatedLessons { get; set; }
    }
}
