// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetTeacherSubjectByTeacherIDResult
    {
        public Guid TeacherSubjectID { get; set; }
        public Guid TeacherID { get; set; }
        public Guid SubjectID { get; set; }
        public string TeacherName { get; set; }
        public string SubjectName { get; set; }
    }
}
