// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class GetUserTripsTodayResult
    {
        public Guid TripId { get; set; }
        public Guid BusId { get; set; }
        public Guid RouteId { get; set; }
        public Guid SchoolId { get; set; }
        public string TripName { get; set; }
        public Guid? Direction { get; set; }
        public TimeSpan DepartureTime { get; set; }
        public TimeSpan? EstimatedArrivalTime { get; set; }
        public int? MaxCapacity { get; set; }
        public bool IsActive { get; set; }
        public Guid CreatedByStaffId { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Notes { get; set; }
        public string RecurringDays { get; set; }
        public Guid? DriverID { get; set; }
        public Guid? AttendantID { get; set; }
        public DateTime? TripDate { get; set; }
        public bool? isRecurring { get; set; }
        public Guid? AcademicLevel { get; set; }
        public bool? DaySchoolOnly { get; set; }
        public bool? SchoolWide { get; set; }
        public bool? RequresParentBookIng { get; set; }
    }
}
