// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_CreateStudentFinanceForExistingStudentsResult
    {
        public Guid StudentFinanceId { get; set; }
        public Guid StudentId { get; set; }
        public Guid? SchoolId { get; set; }
        public string StudentName { get; set; }
    }
}
