// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetStudentTimetableResult
    {
        public Guid TimeslotID { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        [StringLength(50)]
        public string TimeSlotDescription { get; set; }
        [StringLength(50)]
        public string SlotType { get; set; }
        public Guid? DayID { get; set; }
        [StringLength(50)]
        public string DayName { get; set; }
        public Guid? ClassScheduleID { get; set; }
        public Guid? ClassID { get; set; }
        [StringLength(50)]
        public string ClassName { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public Guid? SchoolID { get; set; }
        [StringLength(50)]
        public string TeacherFirstName { get; set; }
        [StringLength(50)]
        public string TeacherLastName { get; set; }
        [StringLength(8)]
        public string EntryType { get; set; }
        public Guid? ScheduledClassID { get; set; }
        public Guid? ActivityID { get; set; }
        [StringLength(100)]
        public string ActivityName { get; set; }
        [StringLength(50)]
        public string LevelName { get; set; }
    }
}
