// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetExpiringSoonMedicationsResult
    {
        public Guid MedicationId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public int Stock { get; set; }
        [StringLength(20)]
        public string Unit { get; set; }
        public DateTime? ExpiryDate { get; set; }
        [StringLength(255)]
        public string BatchNumber { get; set; }
        public Guid? ClinicID { get; set; }
    }
}
