// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetMonthlyPaymentTrendResult
    {
        [StringLength(30)]
        public string Month { get; set; }
        [Column("Amount", TypeName = "decimal(38,2)")]
        public decimal Amount { get; set; }
    }
}
