// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetBusMaintenanceRequestsResult
    {
        public Guid MaintenanceRequestId { get; set; }
        public Guid BusId { get; set; }
        public string RegistrationNumber { get; set; }
        public Guid SchoolId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public DateTime ReportedDate { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public DateTime? CompletedDate { get; set; }
        public Guid ReportedByStaffId { get; set; }
        public string ReportingStaffFirstName { get; set; }
        public string ReportingStaffLastName { get; set; }
        public string EmployeeID { get; set; }
        public Guid? HandledByStaffId { get; set; }
        [Column(TypeName = "decimal(10,2)")]
        public decimal? EstimatedCost { get; set; }
        [Column(TypeName = "decimal(10,2)")]
        public decimal? ActualCost { get; set; }
    }
}
