// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetTeacherTimetableResult
    {
        public Guid ClassScheduleID { get; set; }
        public Guid DayID { get; set; }
        [StringLength(50)]
        public string DayName { get; set; }
        public Guid TimeslotID { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        [StringLength(50)]
        public string SlotType { get; set; }
        public Guid? ClassID { get; set; }
        [StringLength(50)]
        public string ClassName { get; set; }
        public int? AcademicLevel { get; set; }
        [StringLength(50)]
        public string GradeSection { get; set; }
        public Guid TeacherID { get; set; }
        [StringLength(50)]
        public string TeacherFirstName { get; set; }
        [StringLength(50)]
        public string TeacherLastName { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public Guid? SchoolID { get; set; }
    }
}
