// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetClinicDashboardMetricsResult
    {
        public int? CurrentlySickStudents { get; set; }
        public int? ExpiringSoonMedications { get; set; }
        public int? LowStockMedications { get; set; }
        public int? VisitsLast30Days { get; set; }
    }
}
