// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetStudentPaymentsResult
    {
        public Guid PaymentId { get; set; }
        public Guid InvoiceId { get; set; }
        [StringLength(50)]
        public string InvoiceNumber { get; set; }
        [StringLength(50)]
        public string InvoiceType { get; set; }
        public DateTime TermStartDate { get; set; }
        public DateTime TermEndDate { get; set; }
        [Column("AmountPaid", TypeName = "decimal(18,2)")]
        public decimal AmountPaid { get; set; }
        [StringLength(50)]
        public string PaymentMethod { get; set; }
        public DateTime PaymentDate { get; set; }
        public DateTime PaymentCreatedAt { get; set; }
        [Column("InvoiceAmount", TypeName = "decimal(18,2)")]
        public decimal InvoiceAmount { get; set; }
        [Column("InvoicePaidAmount", TypeName = "decimal(18,2)")]
        public decimal InvoicePaidAmount { get; set; }
        [Column("TotalFees", TypeName = "decimal(18,2)")]
        public decimal TotalFees { get; set; }
        [Column("OutstandingAmount", TypeName = "decimal(18,2)")]
        public decimal OutstandingAmount { get; set; }
        [StringLength(50)]
        public string StudentFinanceStatus { get; set; }
    }
}
