// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetStudentLedgerStatementResult
    {
        public Guid Id { get; set; }
<<<<<<< HEAD
        public long LedgerSequence { get; set; }
=======
        public long? LedgerSequence { get; set; }
>>>>>>> dc9665329ab527f497b3db2ffeae5ccb49613c4d
        public DateTime CreatedAt { get; set; }
        [StringLength(10)]
        public string EntryType { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }
        [StringLength(255)]
        public string Description { get; set; }
        [StringLength(50)]
        public string ReferenceType { get; set; }
        public Guid? ReferenceId { get; set; }
        [StringLength(50)]
        public string InvoiceNumber { get; set; }
<<<<<<< HEAD
        public string InvoiceType { get; set; }
        [Column(TypeName = "decimal(38,2)")]
=======
        [StringLength(50)]
        public string InvoiceType { get; set; }
        [Column("RunningBalance", TypeName = "decimal(38,2)")]
>>>>>>> dc9665329ab527f497b3db2ffeae5ccb49613c4d
        public decimal? RunningBalance { get; set; }
    }
}
