// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetFeeStructuresResult
    {
        public Guid Id { get; set; }
        public Guid SchoolId { get; set; }
        public Guid? ClassId { get; set; }
        [StringLength(150)]
        public string Name { get; set; }
        public DateTime TermStartDate { get; set; }
        public DateTime TermEndDate { get; set; }
        [StringLength(20)]
        public string AcademicYear { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}
