// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetFinanceDashboardSummaryResult
    {
        [Column(TypeName = "decimal(18,2)")]
        public decimal? TotalInvoiced { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? TotalCollected { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? OutstandingBalance { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? PaymentsToday { get; set; }
        public int? OverdueInvoices { get; set; }
    }
}
