// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class sp_GetRecentPaymentsResult
    {
        public Guid PaymentId { get; set; }
        public Guid StudentID { get; set; }
        [StringLength(101)]
        public string StudentName { get; set; }
        [StringLength(50)]
        public string InvoiceNumber { get; set; }
        [Column("AmountPaid", TypeName = "decimal(18,2)")]
        public decimal AmountPaid { get; set; }
        [StringLength(50)]
        public string PaymentMethod { get; set; }
        public DateTime PaymentDate { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
