// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class usp_GetParentTripAttendancesResult
    {
        public Guid TripAttendanceId { get; set; }
        public Guid TripId { get; set; }
        public Guid StudentId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string LevelName { get; set; }
        public byte[] ProfilePic { get; set; }
        public DateTime AttendanceDate { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? OnboardTime { get; set; }
        public DateTime? OffboardTime { get; set; }
        [Column("OffboardLatitude", TypeName = "decimal(9,6)")]
        public decimal? OffboardLatitude { get; set; }
        [Column("OffboardLongitude", TypeName = "decimal(9,6)")]
        public decimal? OffboardLongitude { get; set; }
        public Guid? OffboardStopId { get; set; }
        public Guid? OffboardedByUserId { get; set; }
        [StringLength(100)]
        public string TripName { get; set; }
        public Guid? Direction { get; set; }
        public TimeSpan DepartureTime { get; set; }
        public DateTime? TripDate { get; set; }
        public TimeSpan? EstimatedArrivalTime { get; set; }
        public Guid RouteId { get; set; }
        public Guid BusId { get; set; }
    }
}
