// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class usp_GetStaffBySchoolAndRoleResult
    {
        public Guid StaffID { get; set; }
        [StringLength(255)]
        public string StaffName { get; set; }
        [StringLength(255)]
        public string StaffType { get; set; }
        public Guid? SchoolID { get; set; }
        [StringLength(450)]
        public string UserID { get; set; }
        public bool? isDean { get; set; }
        public Guid? DeanForGender { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        [StringLength(2147483647)]
        public string PhoneNumber { get; set; }
    }
}
