// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduSphereDomain.Models
{
    public partial class usp_GetAvailableTripsForParentBookingResult
    {
        public Guid TripId { get; set; }
        public string TripName { get; set; }
        public Guid? Direction { get; set; }
        public TimeSpan DepartureTime { get; set; }
        public TimeSpan? EstimatedArrivalTime { get; set; }
        public Guid RouteId { get; set; }
        public Guid BusId { get; set; }
        public int? MaxCapacity { get; set; }
        public string Notes { get; set; }
        public bool? isRecurring { get; set; }
        public string RecurringDays { get; set; }
        public DateTime? TripDate { get; set; }
        public Guid StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LevelName { get; set; }
        public bool? isDaySchool { get; set; }
        public Guid? ParentID { get; set; }
    }
}
