// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetAttendanceByTeacherAndDateResult
    {
        public Guid StudentAttendanceID { get; set; }
        public DateTime? AttendanceDate { get; set; }
        public Guid? StudentScheduleID { get; set; }
        public bool? LateStatus { get; set; }
        public bool? AttendanceStatus { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ClassName { get; set; }
    }
}
