// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetAttendanceSummaryResult
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Term { get; set; }
        public double? GPA { get; set; }
        public DateTime IssueDate { get; set; }
        public DateTime TermStartDate { get; set; }
        public DateTime TermEndDate { get; set; }
        public int GradeLevel { get; set; }
        public int ExpectedAttendances { get; set; }
        public int AttendanceCount { get; set; }
    }
}
