// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetHostelsBySchoolResult
    {
        public Guid HostelId { get; set; }
        public string HostelName { get; set; }
        public string Gender { get; set; }
        public Guid GenderID { get; set; }
        public int? Capacity { get; set; }
        public string Supervisor { get; set; }
        public Guid? SupervisorID { get; set; }
        public DateTime CreatedAt { get; set; }
        public Guid SchoolId { get; set; }
        public int Occupied { get; set; }
    }
}
