// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetInitializationDataResult
    {
        public Guid? StudentID { get; set; }
        public string RoleName { get; set; }
        public int HideStudentDashboard { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Guid? SchoolID { get; set; }
        public string SchoolName { get; set; }
        public byte[] SchoolLogo { get; set; }
        public bool? HasplagerismEnaabled { get; set; }
    }
}
