// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetRoomsBySchoolResult
    {
        public Guid RoomId { get; set; }
        public Guid HostelId { get; set; }
        public string RoomNumber { get; set; }
        public int MaxOccupancy { get; set; }
        public string RoomType { get; set; }
        public string HostelName { get; set; }
        public Guid? GenderId { get; set; }
        public string GenderDescription { get; set; }
        public int? OccupiedCount { get; set; }
        public bool? IsFull { get; set; }
    }
}
