// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetReportCardsByStudentResult
    {
        public Guid ReportCardID { get; set; }
        public Guid? StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? GradeLevel { get; set; }

        public string LevelName { get; set; }
        public string Term { get; set; }
        [Column(TypeName = "decimal(4,2)")]
        public decimal? GPA { get; set; }
        public DateTime? IssuedDate { get; set; }
        public DateTime? TermStartDate { get; set; }
        public DateTime? TermEndDate { get; set; }
    }
}
