// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetStudentExamDetailsByTeacherResult
    {
        public Guid StudentExamID { get; set; }
        [Column(TypeName = "decimal(5,2)")]
        public decimal? Grade { get; set; }
        public DateTime? SubmissionDate { get; set; }
        public string StudentNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Guid StudentID { get; set; }
        public Guid ExamQuizID { get; set; }
        public string ExamType { get; set; }
        public string Title { get; set; }
        public int TotalMarks { get; set; }
        public DateTime StartDate { get; set; }
        public int? GradeLevel { get; set; }
        public string ClassName { get; set; }

        [NotMapped]
        public string LevelName { get; set; }
    }
}
