// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetStudentsInGradeDetailsResult
    {
        public Guid StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? GradeLevel { get; set; }
        public Guid? ParentID { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string StudentNumber { get; set; }
        public byte[] ProfilePic { get; set; }
        public string UserID { get; set; }
        public DateTime? DateOnBoarded { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    }
}
