// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetStudentPerformanceForCurrentYearResult
    {
        public Guid? StudentID { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? Year { get; set; }
        public string MonthName { get; set; }
        [Column(TypeName = "decimal(38,6)")]
        public decimal? AverageMonthlyScore { get; set; }
        [Column(TypeName = "decimal(38,6)")]
        public decimal PreviousAverage { get; set; }
        public int IsImproving { get; set; }
    }
}
