// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetUserBadgesByUserIDResult
    {
        public Guid UserBadgeID { get; set; }
        public Guid? UserID { get; set; }
        public string BadgeName { get; set; }
        public string BadgeDescription { get; set; }
        public string image_url { get; set; }
        public string BadgeLevel { get; set; }
        public DateTime? DateEarned { get; set; }
    }
}
