// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models.StoreProModels
{
    public partial class GetUpcomingExamsOrQuizzesResult
    {
        public Guid ExamQuizID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Guid TeacherID { get; set; }
        public string ExamType { get; set; }
        public int TotalMarks { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? ClassID { get; set; }
    }
}
