// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AppLicensingAPI.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AppLicensingAPI.Models
{
    public partial interface ILicensingAPIContextProcedures
    {
        Task<List<usp_GetCompanyLicenseStatusResult>> usp_GetCompanyLicenseStatusAsync(Guid? CompanyId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
