// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.Models;

public partial class LicensingAPIContext : DbContext
{
    public LicensingAPIContext(DbContextOptions<LicensingAPIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clients> Clients { get; set; }

    public virtual DbSet<LicenseLogs> LicenseLogs { get; set; }

    public virtual DbSet<Licenses> Licenses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Clients>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Clients__E67E1A245DE6B645");

            entity.HasIndex(e => e.Email, "UQ__Clients__A9D1053458A23FAC").IsUnique();

            entity.Property(e => e.ClientId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(15);
            entity.Property(e => e.ProjectLicense).IsUnicode(false);
        });

        modelBuilder.Entity<LicenseLogs>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__LicenseL__5E54864886BE1ECF");

            entity.Property(e => e.LogId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Timestamp)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.License).WithMany(p => p.LicenseLogs)
                .HasForeignKey(d => d.LicenseId)
                .HasConstraintName("FK_LicenseLogs_Licenses");
        });

        modelBuilder.Entity<Licenses>(entity =>
        {
            entity.HasKey(e => e.LicenseId).HasName("PK__Licenses__72D60082AB320464");

            entity.HasIndex(e => new { e.ClientId, e.Status, e.EndDate }, "IX_Licenses_ClientId_Status_EndDate").IsDescending(false, false, true);

            entity.Property(e => e.LicenseId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.EndDate).HasColumnType("date");
            entity.Property(e => e.LicenseKey)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PlanType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.StartDate).HasColumnType("date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}