// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AppLicensingAPI.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AppLicensingAPI.Models
{
    public partial class LicensingAPIContext
    {
        private ILicensingAPIContextProcedures _procedures;

        public virtual ILicensingAPIContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new LicensingAPIContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ILicensingAPIContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<usp_GetCompanyLicenseStatusResult>().HasNoKey().ToView(null);
        }
    }

    public partial class LicensingAPIContextProcedures : ILicensingAPIContextProcedures
    {
        private readonly LicensingAPIContext _context;

        public LicensingAPIContextProcedures(LicensingAPIContext context)
        {
            _context = context;
        }

        public virtual async Task<List<usp_GetCompanyLicenseStatusResult>> usp_GetCompanyLicenseStatusAsync(Guid? CompanyId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "CompanyId",
                    Value = CompanyId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetCompanyLicenseStatusResult>("EXEC @returnValue = [dbo].[usp_GetCompanyLicenseStatus] @CompanyId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
