// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppLicensingAPI.Models;

public partial class Licenses
{
    public Guid LicenseId { get; set; }

    public Guid ClientId { get; set; }

    public string LicenseKey { get; set; }

    public string PlanType { get; set; }

    public int UserLimit { get; set; }

    public string Status { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual Clients Client { get; set; }

    public virtual ICollection<LicenseLogs> LicenseLogs { get; set; } = new List<LicenseLogs>();
}