// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppLicensingAPI.Models;

public partial class LicenseLogs
{
    public Guid LogId { get; set; }

    public Guid LicenseId { get; set; }

    public string Action { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual Licenses License { get; set; }
}