// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class AiAssesmentResponse
{
    [Key]
    public Guid ResponseID { get; set; }

    public Guid? QuestionID { get; set; }

    [Unicode(false)]
    public string Answer { get; set; }

    [ForeignKey("QuestionID")]
    [InverseProperty("AiAssesmentResponses")]
    public virtual AIAssesmentQuestion Question { get; set; }
}