// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class AIAssesmentQuestion
{
    [Key]
    public Guid QuestionID { get; set; }

    public Guid? AIAssesmentID { get; set; }

    [Unicode(false)]
    public string Question { get; set; }

    [ForeignKey("AIAssesmentID")]
    [InverseProperty("AIAssesmentQuestions")]
    public virtual PharmacyAIAssesment AIAssesment { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<AiAssesmentResponse> AiAssesmentResponses { get; set; } = new List<AiAssesmentResponse>();
}