// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Table("AIAssesmentIssuesFound")]
public partial class AIAssesmentIssuesFound
{
    [Key]
    public Guid IssueID { get; set; }

    public Guid? AIAssesmentID { get; set; }

    [Unicode(false)]
    public string IssueFound { get; set; }

    [ForeignKey("AIAssesmentID")]
    [InverseProperty("AIAssesmentIssuesFounds")]
    public virtual PharmacyAIAssesment AIAssesment { get; set; }
}