// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class City
{
    [Key]
    public Guid CityID { get; set; }

    [Required]
    [StringLength(100)]
    public string CityName { get; set; }

    [StringLength(100)]
    public string Province { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Longitude { get; set; }

    [InverseProperty("BranchLocationNavigation")]
    public virtual ICollection<TenantBranch> TenantBranches { get; set; } = new List<TenantBranch>();
}