// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class ExpenseType
{
    [Key]
    public Guid ExpenseID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ExpenseName { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    public bool? CanBeRequestedByNonAdmin { get; set; }

    [InverseProperty("ExpenseType")]
    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();
}