// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class GetAdminEmailsByTenantResult
    {
        [StringLength(256)]
        public string Email { get; set; }
    }
}
