// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class GetExpenseSummaryResult
    {
        [StringLength(50)]
        public string ExpenseType { get; set; }
        [Column("TotalAmount", TypeName = "decimal(38,0)")]
        public decimal? TotalAmount { get; set; }
        public int? ExpenseCount { get; set; }
    }
}
