// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class GetRadiologyIncomeDetailsResult
    {
        [StringLength(50)]
        public string ScanType { get; set; }
        public int? NumberOfScans { get; set; }
        [Column("TotalAmount", TypeName = "money")]
        public decimal? TotalAmount { get; set; }
    }
}
