// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class GetStockByBranchResult
    {
        [StringLength(50)]
        public string ProductName { get; set; }
        public Guid? BranchID { get; set; }
        public int Stock { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal Price { get; set; }
        public DateTime? ExpiryDate { get; set; }
    }
}
