// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class PatientProfile
{
    [Key]
    public Guid PatientProfileID { get; set; }

    public Guid? UserID { get; set; }

    public Guid? PharmacyID { get; set; }

    [StringLength(255)]
    public string PatientCode { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Gender { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public bool? EmailReciepts { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateCreated { get; set; }

    [Unicode(false)]
    public string FirstName { get; set; }

    [Unicode(false)]
    public string LastName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Unicode(false)]
    public string EmailAddress { get; set; }

    [Column(TypeName = "text")]
    public string Allergies { get; set; }

    [Column(TypeName = "text")]
    public string MedicalConditions { get; set; }

    [Unicode(false)]
    public string EmergencyContactName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EmergencyContactPhone { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string IdentificationNumber { get; set; }

    public bool? isAccountLinked { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    public Guid? UpdatedBy { get; set; }
}