// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class ProductManagementLog
{
    [Key]
    public Guid ChangeLogID { get; set; }

    public Guid? ProductID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ChangedProperty { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChangeDate { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductManagementLogs")]
    public virtual Product Product { get; set; }
}