// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Index("TenantID", Name = "IX_Products_TenantID")]
public partial class Product
{
    [Key]
    public Guid ProductID { get; set; }

    public Guid TenantID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProductName { get; set; }

    public Guid CategoryID { get; set; }

    [Unicode(false)]
    public string Barcode { get; set; }

    [Column(TypeName = "money")]
    public decimal? OrderPricePerUnit { get; set; }

    [Unicode(false)]
    public string Supplier { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("Products")]
    public virtual Product_Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductManagementLog> ProductManagementLogs { get; set; } = new List<ProductManagementLog>();

    [ForeignKey("TenantID")]
    [InverseProperty("Products")]
    public virtual Tenant Tenant { get; set; }
}