// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class RadiologyRequest
{
    [Key]
    public Guid RadiologyID { get; set; }

    [Unicode(false)]
    public string PatientName { get; set; }

    public Guid? ScanTypeID { get; set; }

    [Unicode(false)]
    public string ReferringDoctor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "money")]
    public decimal? ScanPrice { get; set; }

    [Column(TypeName = "text")]
    public string Scanurl { get; set; }

    public Guid? DoneBy { get; set; }

    public Guid? BranchID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "text")]
    public string RadiologistReport { get; set; }

    [Column(TypeName = "text")]
    public string SentraPreliminaryReport { get; set; }

    [Column(TypeName = "text")]
    public string SentraDisclaimer { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReportedDate { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? PriceAtTime { get; set; }

    [ForeignKey("ScanTypeID")]
    [InverseProperty("RadiologyRequests")]
    public virtual RadiologyScanType ScanType { get; set; }
}