// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class RadiologyScanType
{
    [Key]
    public Guid ScanTypeID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ScanType { get; set; }

    [Column(TypeName = "money")]
    public decimal? ScanFee { get; set; }

    public Guid? BranchID { get; set; }

    public Guid? TenantID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    public bool? isActive { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("RadiologyScanTypes")]
    public virtual TenantBranch Branch { get; set; }

    [InverseProperty("ScanType")]
    public virtual ICollection<RadiologyRequest> RadiologyRequests { get; set; } = new List<RadiologyRequest>();
}