// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class SaleItem
{
    [Key]
    public Guid SaleItemID { get; set; }

    public Guid SaleID { get; set; }

    public Guid ProductID { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal PriceAtTimeOfSale { get; set; }

    [ForeignKey("SaleID")]
    [InverseProperty("SaleItems")]
    public virtual Sale Sale { get; set; }
}