// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Table("ServicesOffered")]
public partial class ServicesOffered
{
    [Key]
    public Guid ServiceID { get; set; }

    public Guid TenantID { get; set; }

    public Guid? BranchID { get; set; }

    [Required]
    [StringLength(200)]
    public string ServiceName { get; set; }

    [StringLength(500)]
    public string ServiceDescription { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal DefaultAmount { get; set; }

    public bool IsActive { get; set; }

    [StringLength(100)]
    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<ServiceIncome> ServiceIncomes { get; set; } = new List<ServiceIncome>();
}