// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class sp_GetPatientProfileByIdentificationResult
    {
        public Guid PatientProfileID { get; set; }
        public Guid? UserID { get; set; }
        public Guid? PharmacyID { get; set; }
        [StringLength(255)]
        public string PatientCode { get; set; }
        [StringLength(2147483647)]
        public string FirstName { get; set; }
        [StringLength(2147483647)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string PhoneNumber { get; set; }
        [StringLength(2147483647)]
        public string EmailAddress { get; set; }
        [StringLength(10)]
        public string Gender { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Allergies { get; set; }
        public string MedicalConditions { get; set; }
        [StringLength(2147483647)]
        public string EmergencyContactName { get; set; }
        [StringLength(50)]
        public string EmergencyContactPhone { get; set; }
        [StringLength(50)]
        public string IdentificationNumber { get; set; }
        public bool? isAccountLinked { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
    }
}
