// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class sp_GetInventoryByProductResult
    {
        public Guid InventoryID { get; set; }
        public Guid? ProductID { get; set; }
        public Guid? BranchID { get; set; }
        public int Stock { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal Price { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
    }
}
