// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class sp_GetPharmacyPerformanceSummaryResult
    {
        public Guid BranchID { get; set; }
        public Guid? TenantID { get; set; }
        [StringLength(2147483647)]
        public string BranchName { get; set; }
        [StringLength(9)]
        public string Type { get; set; }
        public Guid? ProductID { get; set; }
        [StringLength(50)]
        public string ProductName { get; set; }
        public int? CurrentStock { get; set; }
        [Column("CurrentPrice", TypeName = "money")]
        public decimal? CurrentPrice { get; set; }
        public DateTime? ExpiryDate { get; set; }
        [Column("TotalSalesAmount", TypeName = "money")]
        public decimal? TotalSalesAmount { get; set; }
        public Guid? ServiceID { get; set; }
        [StringLength(200)]
        public string ServiceName { get; set; }
        [Column("ServiceIncome", TypeName = "decimal(38,2)")]
        public decimal? ServiceIncome { get; set; }
    }
}
