// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class TenantAIToken
{
    [Key]
    public Guid TentantTokenID { get; set; }

    public Guid? TenantID { get; set; }

    public int? Tokens { get; set; }
}