// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

public partial class TokenSubscription
{
    [Key]
    public Guid ID { get; set; }

    public Guid? TenantID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PaymentMethod { get; set; }

    [Unicode(false)]
    public string TransactionReference { get; set; }

    [Unicode(false)]
    public string transactionImageUrl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    public bool? isCompleted { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ApprovedBy { get; set; }
}