// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class usp_GetRestockRequestsByTenantResult
    {
        public Guid RequestID { get; set; }
        public Guid? RequestedItem { get; set; }
        [StringLength(50)]
        public string ProductName { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal Price { get; set; }
        public int StockRemaining { get; set; }
        [StringLength(2147483647)]
        public string RequestedBy { get; set; }
        public DateTime? RequestedDate { get; set; }
        public DateTime? ApprovalDate { get; set; }
        public Guid? StatusID { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(2147483647)]
        public string BranchName { get; set; }
        [StringLength(2147483647)]
        public string Supplier { get; set; }
        public DateTime? ExpiryDate { get; set; }
    }
}
