// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class usp_GetPendingPrescriptionsByTenantResult
    {
        public Guid PrescriptionID { get; set; }
        public Guid? PatientProfileID { get; set; }
        public Guid? TenantID { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? ApprovedBy { get; set; }
        public Guid? DispensedBy { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        public DateTime? PrescriptionDate { get; set; }
        public string Notes { get; set; }
        [StringLength(2147483647)]
        public string DigitalCopy { get; set; }
        [Column("TotalAmount", TypeName = "money")]
        public decimal? TotalAmount { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public Guid? BranchID { get; set; }
    }
}
