// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class usp_GetSalesDashboardByTenantResult
    {
        public Guid? TenantID { get; set; }
        public int? SaleYear { get; set; }
        [Column("TotalYearSales", TypeName = "money")]
        public decimal? TotalYearSales { get; set; }
        [Column("JanSales", TypeName = "money")]
        public decimal? JanSales { get; set; }
        [Column("FebSales", TypeName = "money")]
        public decimal? FebSales { get; set; }
        [Column("MarSales", TypeName = "money")]
        public decimal? MarSales { get; set; }
        [Column("AprSales", TypeName = "money")]
        public decimal? AprSales { get; set; }
        [Column("MaySales", TypeName = "money")]
        public decimal? MaySales { get; set; }
        [Column("JunSales", TypeName = "money")]
        public decimal? JunSales { get; set; }
        [Column("JulSales", TypeName = "money")]
        public decimal? JulSales { get; set; }
        [Column("AugSales", TypeName = "money")]
        public decimal? AugSales { get; set; }
        [Column("SepSales", TypeName = "money")]
        public decimal? SepSales { get; set; }
        [Column("OctSales", TypeName = "money")]
        public decimal? OctSales { get; set; }
        [Column("NovSales", TypeName = "money")]
        public decimal? NovSales { get; set; }
        [Column("DecSales", TypeName = "money")]
        public decimal? DecSales { get; set; }
    }
}
