// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class usp_GetHighSellingItemsByTenantResult
    {
        public Guid TenantID { get; set; }
        public Guid ProductID { get; set; }
        [StringLength(50)]
        public string ProductName { get; set; }
        public int? TotalQuantitySold { get; set; }
        [Column("TotalRevenue", TypeName = "money")]
        public decimal? TotalRevenue { get; set; }
    }
}
