// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class usp_GetRecentSalesByTenantResult
    {
        public Guid TenantID { get; set; }
        [StringLength(50)]
        public string ProductName { get; set; }
        public Guid SaleID { get; set; }
        public Guid BranchID { get; set; }
        public Guid SoldBy { get; set; }
        [Column("TotalAmount", TypeName = "money")]
        public decimal TotalAmount { get; set; }
        public Guid? PaymentMethod { get; set; }
        public DateTime SaleDate { get; set; }
    }
}
