// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class usp_GetNetProfitResult
    {
        [Column("TotalSales", TypeName = "decimal(18,2)")]
        public decimal? TotalSales { get; set; }
        [Column("TotalServiceIncome", TypeName = "decimal(18,2)")]
        public decimal? TotalServiceIncome { get; set; }
        [Column("TotalRadiologyIncome", TypeName = "decimal(18,2)")]
        public decimal? TotalRadiologyIncome { get; set; }
        [Column("TotalExpenses", TypeName = "decimal(18,2)")]
        public decimal? TotalExpenses { get; set; }
        [Column("NetProfit", TypeName = "decimal(18,2)")]
        public decimal? NetProfit { get; set; }
    }
}
