// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppLicensingAPI.MedicoreModels
{
    public partial class usp_GetLowStockByTenantResult
    {
        public Guid TenantID { get; set; }
        public Guid? BranchID { get; set; }
        public int? LowStockItemCount { get; set; }
    }
}
