// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Keyless]
public partial class vw_HighTurnoverItem
{
    public Guid TenantID { get; set; }

    public Guid ProductID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProductName { get; set; }

    [Column(TypeName = "money")]
    public decimal? TotalRevenue { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastRestockDate { get; set; }
}