// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Keyless]
public partial class vw_PatientPrescription
{
    public Guid PrescriptionID { get; set; }

    public Guid? PatientProfileID { get; set; }

    [Unicode(false)]
    public string PatientName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Unicode(false)]
    public string EmailAddress { get; set; }

    [StringLength(255)]
    public string PatientCode { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Gender { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    [Column(TypeName = "text")]
    public string Allergies { get; set; }

    [Column(TypeName = "text")]
    public string MedicalConditions { get; set; }

    [Unicode(false)]
    public string EmergencyContactName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EmergencyContactPhone { get; set; }

    public Guid? TenantID { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? ApprovedBy { get; set; }

    public Guid? DispensedBy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PrescriptionDate { get; set; }

    [Column(TypeName = "text")]
    public string Notes { get; set; }

    [Unicode(false)]
    public string DigitalCopy { get; set; }

    [Column(TypeName = "money")]
    public decimal? TotalAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public Guid? BranchID { get; set; }

    public Guid? PresItemID { get; set; }

    public Guid? ProductID { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal? UnityPrice { get; set; }

    [Column(TypeName = "text")]
    public string Instructions { get; set; }

    public int? DispensedQty { get; set; }
}