// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Keyless]
public partial class vw_RecentSale
{
    public Guid TenantID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProductName { get; set; }

    public Guid SaleID { get; set; }

    public Guid BranchID { get; set; }

    public Guid SoldBy { get; set; }

    [Column(TypeName = "money")]
    public decimal TotalAmount { get; set; }

    public Guid? PaymentMethod { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SaleDate { get; set; }
}