// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Keyless]
public partial class vw_SalesDashboard
{
    public Guid? TenantID { get; set; }

    public int? SaleYear { get; set; }

    [Column(TypeName = "money")]
    public decimal? TotalYearSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? JanSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? FebSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? MarSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? AprSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? MaySales { get; set; }

    [Column(TypeName = "money")]
    public decimal? JunSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? JulSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? AugSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? SepSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? OctSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? NovSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? DecSales { get; set; }
}