// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppLicensingAPI.MedicoreModels;

[Keyless]
public partial class vwAllTenant
{
    public Guid TenantID { get; set; }

    [StringLength(255)]
    public string TenantName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime JoinDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EmailAddress { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ContactNo { get; set; }
}