// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class AcademicLevel
{
    public Guid AcademicLevelID { get; set; }

    public Guid? SchoolID { get; set; }

    public int? LevelInt { get; set; }

    public string LevelName { get; set; }

    public string GroupName { get; set; }

    public int? SortOrder { get; set; }

    public bool? isActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}