// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class AIAdviceLog
{
    public Guid AdviceID { get; set; }

    public Guid BatchID { get; set; }

    public DateTime GeneratedOn { get; set; }

    public string AdviceText { get; set; }

    public bool Used { get; set; }

    public virtual InventoryBatch Batch { get; set; }
}