// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Bus
{
    public Guid BusId { get; set; }

    public Guid SchoolId { get; set; }

    public string RegistrationNumber { get; set; }

    public int Capacity { get; set; }

    public Guid? DriverStaffId { get; set; }

    public string LicensePlateNumber { get; set; }

    public string FuelType { get; set; }

    public string Model { get; set; }

    public Guid FuelTypeId { get; set; }

    public int? ModelYear { get; set; }

    public int CurrentMileageKm { get; set; }

    public decimal? AverageKmPerLitre { get; set; }

    public DateTime? LastServiceDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BusAssignment> BusAssignments { get; set; } = new List<BusAssignment>();

    public virtual ICollection<BusFuelLog> BusFuelLogs { get; set; } = new List<BusFuelLog>();

    public virtual FuelType FuelTypeNavigation { get; set; }

    public virtual School School { get; set; }
}