// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class BusFuelLog
{
    public Guid FuelLogId { get; set; }

    public Guid BusId { get; set; }

    public Guid SchoolId { get; set; }

    public DateTime FuelDate { get; set; }

    public string FuelType { get; set; }

    public decimal LitresAdded { get; set; }

    public decimal CostPerLitre { get; set; }

    public decimal? TotalCost { get; set; }

    public int OdometerReading { get; set; }

    public Guid LoggedByStaffId { get; set; }

    public string Remarks { get; set; }

    public Guid? FuelStationId { get; set; }

    public Guid? StationId { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual FuelStation FuelStation { get; set; }

    public virtual School School { get; set; }
}