// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class BusMaintenanceRequest
{
    public Guid MaintenanceRequestId { get; set; }

    public Guid BusId { get; set; }

    public Guid SchoolId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public string Priority { get; set; }

    public DateTime ReportedDate { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public Guid ReportedByStaffId { get; set; }

    public Guid? HandledByStaffId { get; set; }

    public decimal? EstimatedCost { get; set; }

    public decimal? ActualCost { get; set; }
}