// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class BusRoute
{
    public Guid RouteId { get; set; }

    public Guid? BusId { get; set; }

    public string Name { get; set; }

    public Guid? SchoolId { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual ICollection<BusStop> BusStops { get; set; } = new List<BusStop>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}