// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class BusStop
{
    public Guid StopId { get; set; }

    public Guid RouteId { get; set; }

    public string Name { get; set; }

    public int Sequence { get; set; }

    public virtual BusRoute Route { get; set; }
}