// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ChatMessage
{
    public Guid Id { get; set; }

    public string UserId { get; set; }

    public string GroupName { get; set; }

    public string Message { get; set; }

    public DateTime? Timestamp { get; set; }

    public string ReciepientId { get; set; }
}