// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ClassTeacher
{
    public Guid ClassTeacherID { get; set; }

    public Guid? TeacherID { get; set; }

    public Guid? AcademicLevelID { get; set; }

    public Guid? SchoolID { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateUpdated { get; set; }

    public string CreatedBy { get; set; }

    public Guid? LevelSectionID { get; set; }

    public virtual AcademicLevel AcademicLevel { get; set; }

    public virtual LevelSection LevelSection { get; set; }

    public virtual School School { get; set; }

    public virtual Teacher Teacher { get; set; }
}