// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class Class
{
    public Guid ClassID { get; set; }

    public string ClassName { get; set; }

    public Guid? TeacherID { get; set; }

    public int? AcademicLevel { get; set; }

    public Guid? SChoolID { get; set; }

    public string GradeSection { get; set; }

    public string LevelName { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual ICollection<ClassSchedule> ClassSchedules { get; set; } = new List<ClassSchedule>();

    public virtual ICollection<ExamQuizTestHeader> ExamQuizTestHeaders { get; set; } = new List<ExamQuizTestHeader>();

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<ReportCardDetail> ReportCardDetails { get; set; } = new List<ReportCardDetail>();

    public virtual School SChool { get; set; }

    public virtual ICollection<StudentClass> StudentClasses { get; set; } = new List<StudentClass>();

    public virtual Teacher Teacher { get; set; }
    [NotMapped]
    public bool HasCustomPeriods { get; set; } = false;
    [NotMapped]
    public bool IsCore { get; set; }  // admin can check this for core subjects
}