// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ClassSchedule
{
    public Guid ClassScheduleID { get; set; }

    public Guid? ClassID { get; set; }

    public Guid? TimeSlotID { get; set; }

    public Guid? DayOfTheWeekID { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public Guid? SchoolID { get; set; }

    public bool IsDoublePeriod { get; set; }

    public int? SlotOrder { get; set; }

    public bool IsFiller { get; set; }

    public Guid? ScheduledActivity { get; set; }

    public virtual Class Class { get; set; }

    public virtual DayofTheWeek DayOfTheWeek { get; set; }

    public virtual TimeTableActivity ScheduledActivityNavigation { get; set; }

    public virtual ICollection<StudentClassSchedule> StudentClassSchedules { get; set; } = new List<StudentClassSchedule>();

    public virtual TimeSlot TimeSlot { get; set; }
}