// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ClientAdmin
{
    public Guid AdminID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public Guid? SchoolID { get; set; }

    public string Gender { get; set; }

    public byte[] ProfilePic { get; set; }

    public string MobileNumber { get; set; }

    public string Nationality { get; set; }

    public string City { get; set; }

    public string UserID { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual School School { get; set; }
}