// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class ClinicMedication
{
    public Guid MedicationId { get; set; }

    public string Name { get; set; }

    public int Stock { get; set; }

    public string Unit { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public Guid? ClinicID { get; set; }

    public string BatchNumber { get; set; }

    public virtual ICollection<ClinicMedicationLog> ClinicMedicationLogs { get; set; } = new List<ClinicMedicationLog>();
    [NotMapped]
    public string ClinicName { get; set; }
}