// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ClinicMedicationLog
{
    public Guid LogId { get; set; }

    public Guid VisitId { get; set; }

    public Guid MedicationId { get; set; }

    public int QuantityUsed { get; set; }

    public virtual ClinicMedication Medication { get; set; }

    public virtual ClinicVisit Visit { get; set; }
}