// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ClinicStaff
{
    public Guid StaffId { get; set; }

    public Guid ClinicId { get; set; }

    public string FullName { get; set; }

    public string Role { get; set; }

    public string Contact { get; set; }

    public string UserID { get; set; }

    public string EmployeeID { get; set; }

    public Guid? SchoolID { get; set; }

    public virtual Clinic Clinic { get; set; }
}