// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class DiningAttendance
{
    public Guid AttendanceId { get; set; }

    public Guid StudentId { get; set; }

    public Guid MealId { get; set; }

    public DateTime Date { get; set; }

    public DateTime MarkedAt { get; set; }

    public virtual Meal Meal { get; set; }
}