// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class DiningSpecialDiet
{
    public Guid DietId { get; set; }

    public Guid StudentId { get; set; }

    public string DietType { get; set; }

    public string Description { get; set; }
}