// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class DiningHall
{
    public Guid DiningHallId { get; set; }

    public Guid SchoolId { get; set; }

    public string Name { get; set; }

    public int? Capacity { get; set; }

    public string Location { get; set; }

    public virtual ICollection<Meal> Meals { get; set; } = new List<Meal>();

    public virtual School School { get; set; }
}