// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ExamQuizTestHeader
{
    public Guid ExamQuizID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Guid TeacherID { get; set; }

    public string ExamType { get; set; }

    public int TotalMarks { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public Guid? ClassID { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<ExamQuizTestQuestion> ExamQuizTestQuestions { get; set; } = new List<ExamQuizTestQuestion>();

    public virtual ICollection<StudentExamsTestsAndQuiz> StudentExamsTestsAndQuizzes { get; set; } = new List<StudentExamsTestsAndQuiz>();

    public virtual Teacher Teacher { get; set; }
}