// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ExamTestQuizMultipleChoiceAnswer
{
    public Guid MultipleChoiceID { get; set; }

    public string MultipleChoiceLetter { get; set; }

    public Guid? ExamTestQuizQuestionID { get; set; }

    public string MuiltpleChoiceAnswer { get; set; }

    public bool? IsCorrectAnswer { get; set; }

    public virtual ExamQuizTestQuestion ExamTestQuizQuestion { get; set; }
}