// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class ExamQuizTestQuestion
{
    public Guid QuestionID { get; set; }

    public Guid ExamQuizID { get; set; }

    public string QuestionText { get; set; }

    public int Marks { get; set; }

    public string QuestionType { get; set; }

    public string Options { get; set; }

    public string CorrectAnswer { get; set; }

    public virtual ExamQuizTestHeader ExamQuiz { get; set; }

    public virtual ICollection<StudentExamQuizAndTestAnswer> StudentExamQuizAndTestAnswers { get; set; } = new List<StudentExamQuizAndTestAnswer>();
    [NotMapped]
    public int? QuestionNumber { get; set; }
}