// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class FuelType
{
    public Guid FuelTypeId { get; set; }

    public string FuelCode { get; set; }

    public string FuelName { get; set; }

    public bool IsLiquidFuel { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();
}