// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class FuelStation
{
    public Guid FuelStationId { get; set; }

    public Guid SchoolId { get; set; }

    public string StationName { get; set; }

    public string Location { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BusFuelLog> BusFuelLogs { get; set; } = new List<BusFuelLog>();
}