// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Gender
{
    public Guid GenderId { get; set; }

    public string GenderDescription { get; set; }
}