// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Grade
{
    public Guid GradeID { get; set; }

    public Guid? StudentID { get; set; }

    public Guid? AssignmentID { get; set; }

    public decimal? Grade1 { get; set; }

    public DateTime? DateAssigned { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual Student Student { get; set; }
}