// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Hostel
{
    public Guid HostelId { get; set; }

    public string HostelName { get; set; }

    public Guid? Gender { get; set; }

    public int? Capacity { get; set; }

    public Guid? SupervisorStaffId { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid SchoolId { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();

    public virtual School School { get; set; }
}