// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class InventoryBatch
{
    public Guid BatchID { get; set; }

    public Guid FoodItemID { get; set; }

    public decimal Quantity { get; set; }

    public DateTime ReceivedDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string StorageLocation { get; set; }

    public decimal? CurrentTemp { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public bool AIAdviceGenerated { get; set; }

    public virtual ICollection<AIAdviceLog> AIAdviceLogs { get; set; } = new List<AIAdviceLog>();

    public virtual FoodItem FoodItem { get; set; }
}