// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Lesson
{
    public Guid LessonID { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public Guid? ClassID { get; set; }

    public Guid? TeacherID { get; set; }

    public DateTime? DatePosted { get; set; }

    public int? Rating { get; set; }

    public int? NumberOfRatings { get; set; }

    public bool? Active { get; set; }

    public string url { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<CourseDetail> CourseDetails { get; set; } = new List<CourseDetail>();

    public virtual ICollection<StudentCompletedLesson> StudentCompletedLessons { get; set; } = new List<StudentCompletedLesson>();

    public virtual Teacher Teacher { get; set; }
}