// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class LessonMedium
{
    public Guid ImageID { get; set; }

    public Guid? LessonID { get; set; }

    public string Url { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Caption { get; set; }
}