// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class LevelSection
{
    public Guid LevelSectionID { get; set; }

    public Guid AcademicLevelID { get; set; }

    public string SectionCode { get; set; }

    public Guid SchoolID { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual AcademicLevel AcademicLevel { get; set; }

    public virtual ICollection<ClassTeacher> ClassTeachers { get; set; } = new List<ClassTeacher>();
}