// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class MaintainanceRequest
{
    public Guid RequestID { get; set; }

    public Guid HostelID { get; set; }

    public Guid? RoomID { get; set; }

    public string ProblemDescription { get; set; }

    public string ReportedBy { get; set; }

    public DateTime? DateReported { get; set; }

    public DateTime? DateResolved { get; set; }

    public string Status { get; set; }

    public virtual Hostel Hostel { get; set; }

    public virtual Room Room { get; set; }

    public virtual ICollection<StudentDamageReport> StudentDamageReports { get; set; } = new List<StudentDamageReport>();
}