// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Meal
{
    public Guid MealId { get; set; }

    public Guid DiningHallId { get; set; }

    public string Name { get; set; }

    public TimeSpan TimeStart { get; set; }

    public TimeSpan TimeEnd { get; set; }

    public virtual ICollection<DiningAttendance> DiningAttendances { get; set; } = new List<DiningAttendance>();

    public virtual DiningHall DiningHall { get; set; }

    public virtual ICollection<DiningMenu> DiningMenus { get; set; } = new List<DiningMenu>();
}