// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class MeasurementUnit
{
    public Guid UnitId { get; set; }

    public string Name { get; set; }

    public string Symbol { get; set; }

    public string UnitType { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<FoodItem> FoodItems { get; set; } = new List<FoodItem>();
}