// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class MultipleChoiceAssignmentAnswer
{
    public Guid MultipleChoiceID { get; set; }

    public string MultipleChoiceLetter { get; set; }

    public Guid? AssignmentQuestionID { get; set; }

    public string MuiltpleChoiceAnswer { get; set; }

    public bool? IsCorrectAnswer { get; set; }

    public virtual AssignmentQuestion AssignmentQuestion { get; set; }
}