// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Notification
{
    public Guid NotificationID { get; set; }

    public string Message { get; set; }

    public DateTime? DateSent { get; set; }

    public bool? IsRead { get; set; }
}