// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class Parent
{
    public Guid ParentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string UserId { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string Gender { get; set; }

    public byte[] ProfilePic { get; set; }

    public Guid? SchoolID { get; set; }

    public virtual School School { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
    [NotMapped]
    public string GeneratedUserName { get; set; }
    [NotMapped]
    public string StudentNumbersRaw { get; set; }
}