// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class ReportCard
{
    public Guid ReportCardID { get; set; }

    public Guid? StudentID { get; set; }

    public string Term { get; set; }

    public decimal? GPA { get; set; }

    public DateTime? IssuedDate { get; set; }

    public DateTime? TermStartDate { get; set; }

    public DateTime? TermEndDate { get; set; }

    public int? GradeLevel { get; set; }

    public string GradeSection { get; set; }

    public Guid? SchoolID { get; set; }

    public virtual ICollection<ReportCardDetail> ReportCardDetails { get; set; } = new List<ReportCardDetail>();

    public virtual Student Student { get; set; }
}