// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class ReportCardDetail
{
    public Guid ReportCardDetailID { get; set; }

    public Guid? ReportCardID { get; set; }

    public Guid? ClassID { get; set; }

    public double? Score { get; set; }

    public string Grade { get; set; }

    public double? GPA { get; set; }

    public virtual Class Class { get; set; }

    public virtual ReportCard ReportCard { get; set; }
   
}