// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class RoomAssetConditionEvent
{
    public Guid Id { get; set; }

    public Guid StudentRoomLogId { get; set; }

    public Guid RoomAssetId { get; set; }

    public DateTime EventDate { get; set; }

    public string ConditionStatus { get; set; }

    public string Notes { get; set; }

    public Guid ReportedByStaffId { get; set; }

    public Guid? MaintenanceRequestId { get; set; }

    public virtual RoomAsset RoomAsset { get; set; }

    public virtual ICollection<StudentDamageReport> StudentDamageReports { get; set; } = new List<StudentDamageReport>();

    public virtual StudentRoomLog StudentRoomLog { get; set; }
}