// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Room
{
    public Guid RoomId { get; set; }

    public Guid HostelId { get; set; }

    public string RoomNumber { get; set; }

    public int MaxOccupancy { get; set; }

    public string RoomType { get; set; }

    public virtual Hostel Hostel { get; set; }

    public virtual ICollection<RoomAllocation> RoomAllocations { get; set; } = new List<RoomAllocation>();
}