// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class RoomAsset
{
    public Guid Id { get; set; }

    public Guid RoomId { get; set; }

    public string Name { get; set; }

    public string AssetType { get; set; }

    public Guid AssetTypeId { get; set; }

    public virtual RoomAssetType AssetTypeNavigation { get; set; }

    public virtual Room Room { get; set; }

    public virtual ICollection<RoomAssetConditionEvent> RoomAssetConditionEvents { get; set; } = new List<RoomAssetConditionEvent>();

    public virtual ICollection<RoomAssetCondition> RoomAssetConditions { get; set; } = new List<RoomAssetCondition>();
}