// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class School
{
    public Guid SchoolID { get; set; }

    public string SchoolName { get; set; }

    public byte[] SchoolLogo { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual ICollection<ClientAdmin> ClientAdmins { get; set; } = new List<ClientAdmin>();

    public virtual ICollection<Parent> Parents { get; set; } = new List<Parent>();

    public virtual ICollection<Teacher> Teachers { get; set; } = new List<Teacher>();
}