// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Staff
{
    public Guid StaffID { get; set; }

    public string StaffName { get; set; }

    public string StaffType { get; set; }

    public Guid? SchoolID { get; set; }

    public string UserID { get; set; }

    public bool? isDean { get; set; }

    public Guid? DeanForGender { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public virtual Gender DeanForGenderNavigation { get; set; }

    public virtual School School { get; set; }
}