// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class StudentCompletedLesson
{
    public Guid StudentLessonCompletionID { get; set; }

    public Guid? StudentID { get; set; }

    public Guid? LessonID { get; set; }

    public DateTime? CompletionDate { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual Student Student { get; set; }
}