// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class StudentClassSchedule
{
    public Guid StudentClassScheduleID { get; set; }

    public Guid? StudentID { get; set; }

    public Guid? ScheduleID { get; set; }

    public virtual ClassSchedule Schedule { get; set; }

    public virtual Student Student { get; set; }
}