// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class StudentExamQuizAndTestAnswer
{
    public Guid StudentExamAnswerID { get; set; }

    public Guid? QuestionID { get; set; }

    public string AnswerText { get; set; }

    public DateTime? AnswerDate { get; set; }

    public int? MarksObtained { get; set; }

    public bool? isCorrect { get; set; }

    public bool? isWrong { get; set; }

    public Guid? HeaderID { get; set; }

    public virtual StudentExamsTestsAndQuiz Header { get; set; }

    public virtual ExamQuizTestQuestion Question { get; set; }
}