// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class StudentAttendance
{
    public Guid StudentAttendanceID { get; set; }

    public DateTime? AttendanceDate { get; set; }

    public Guid? StudentScheduleID { get; set; }

    public bool? LateStatus { get; set; }

    public bool? AttendanceStatus { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? Marked { get; set; }
}