// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class Student
{
    public Guid StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? AcademicLevel { get; set; }

    public Guid? ParentID { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string StudentNumber { get; set; }

    public byte[] ProfilePic { get; set; }

    public string UserID { get; set; }

    public DateTime? DateOnBoarded { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public Guid? SchoolID { get; set; }

    public string GradeSection { get; set; }

    public string LevelName { get; set; }

    public bool? PaymentStatus { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual Parent Parent { get; set; }

    public virtual ICollection<ReportCard> ReportCards { get; set; } = new List<ReportCard>();

    public virtual ICollection<StudentAssignment> StudentAssignments { get; set; } = new List<StudentAssignment>();

    public virtual ICollection<StudentClassSchedule> StudentClassSchedules { get; set; } = new List<StudentClassSchedule>();

    public virtual ICollection<StudentClass> StudentClasses { get; set; } = new List<StudentClass>();

    public virtual ICollection<StudentCompletedLesson> StudentCompletedLessons { get; set; } = new List<StudentCompletedLesson>();

    public virtual ICollection<StudentExamsTestsAndQuiz> StudentExamsTestsAndQuizzes { get; set; } = new List<StudentExamsTestsAndQuiz>();

    [NotMapped]
    public string Email { get; set; }
    [NotMapped]
    public string GeneratedUserName { get; set; }
}