// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

/// <summary>
/// Persisted, per-school scheduling policy for one subject (Class). Replaces the transient
/// per-run configuration the old SmartTimeTableGenerator page collected in the browser and
/// posted with every generation request.
/// </summary>
public partial class SubjectScheduleConfig
{
    public Guid SubjectScheduleConfigID { get; set; }

    public Guid ClassID { get; set; }

    public Guid SchoolID { get; set; }

    public bool IsCore { get; set; }

    public int WeeklyPeriods { get; set; }

    public int RequiredDoubles { get; set; }

    /// <summary>Stored as tinyint; see UniversalModels.TimeTabling.SubjectTimePreference.</summary>
    public byte TimePreference { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual Class Class { get; set; }
}
