// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

/// <summary>
/// "ClassID must not be scheduled immediately after CannotFollowClassID." One row per ordered
/// pair, per school.
/// </summary>
public partial class SubjectAdjacencyRule
{
    public Guid SubjectAdjacencyRuleID { get; set; }

    public Guid ClassID { get; set; }

    public Guid CannotFollowClassID { get; set; }

    public Guid SchoolID { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Class Class { get; set; }

    public virtual Class CannotFollowClass { get; set; }
}
