// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class Teacher
{
    public Guid TeacherID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string ContactNo { get; set; }

    public string EmailAddress { get; set; }

    public string Gender { get; set; }

    public DateTime? DateEngaged { get; set; }

    public DateTime? DateTerminated { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public byte[] ProfilePic { get; set; }

    public string UserID { get; set; }

    public string Nationality { get; set; }

    public string City { get; set; }

    public string EmployeeID { get; set; }

    public Guid? SchoolID { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual ICollection<ExamQuizTestHeader> ExamQuizTestHeaders { get; set; } = new List<ExamQuizTestHeader>();

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual School School { get; set; }

    public virtual ICollection<TeacherSubjectNormalized> TeacherSubjectNormalizeds { get; set; } = new List<TeacherSubjectNormalized>();
    [NotMapped]
    public string GeneratedUserName { get; set; }
}