// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDUSphereSharedProject.Models;

public partial class TimeTableActivity
{
    public Guid ActivityID { get; set; }

    public string ActivityName { get; set; }

    public int? DefaultDuration { get; set; }

    public string OptionalNotes { get; set; }

    public bool MustBeMorning { get; set; }

    public bool MustBeAfternoon { get; set; }

    public virtual ICollection<ClassSchedule> ClassSchedules { get; set; } = new List<ClassSchedule>();
    [NotMapped]
    public List<string> CannotFollow { get; set; } = new();

}