// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class TimetableOverride
{
    public Guid TimetableOverrideID { get; set; }

    public int AcademicLevel { get; set; }

    public string GradeSection { get; set; }

    public string StudentGroup { get; set; }

    public Guid DayOfTheWeekID { get; set; }

    public Guid TimeSlotID { get; set; }

    public Guid ReplacementClassID { get; set; }

    public string Reason { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }
}