// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class TripAttendance
{
    public Guid TripAttendanceId { get; set; }

    public Guid TripId { get; set; }

    public Guid StudentId { get; set; }

    public DateTime AttendanceDate { get; set; }

    public string Status { get; set; }

    public DateTime CreatedDate { get; set; }
}