// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Trip
{
    public Guid TripId { get; set; }

    public Guid BusId { get; set; }

    public Guid RouteId { get; set; }

    public Guid SchoolId { get; set; }

    public string TripName { get; set; }

    public Guid? Direction { get; set; }

    public TimeSpan DepartureTime { get; set; }

    public TimeSpan? EstimatedArrivalTime { get; set; }

    public int? MaxCapacity { get; set; }

    public bool? IsActive { get; set; }

    public Guid CreatedByStaffId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Notes { get; set; }

    public string RecurringDays { get; set; }

    public Guid? DriverID { get; set; }

    public Guid? AttendantID { get; set; }

    public DateTime? TripDate { get; set; }

    public bool? isRecurring { get; set; }

    public Guid? AcademicLevel { get; set; }

    public bool? DaySchoolOnly { get; set; }

    public bool? SchoolWide { get; set; }

    public bool? RequresParentBookIng { get; set; }

    public virtual BusRoute Route { get; set; }

    public virtual ICollection<TripBooking> TripBookings { get; set; } = new List<TripBooking>();

    public virtual ICollection<TripSchedule> TripSchedules { get; set; } = new List<TripSchedule>();

    public virtual ICollection<TripTripType> TripTripTypes { get; set; } = new List<TripTripType>();
}