// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class Trip
{
    public Guid TripId { get; set; }

    public Guid BusId { get; set; }

    public Guid RouteId { get; set; }

    public Guid SchoolId { get; set; }

    public string TripName { get; set; }

    public Guid? Direction { get; set; }

    public TimeSpan DepartureTime { get; set; }

    public TimeSpan? EstimatedArrivalTime { get; set; }

    public int? MaxCapacity { get; set; }

    public bool? IsActive { get; set; }

    public int CreatedByStaffId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Notes { get; set; }

    public string RecurringDays { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual TripDirection DirectionNavigation { get; set; }

    public virtual BusRoute Route { get; set; }

    public virtual ICollection<TripBooking> TripBookings { get; set; } = new List<TripBooking>();

    public virtual ICollection<TripSchedule> TripSchedules { get; set; } = new List<TripSchedule>();
}