// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class TripBooking
{
    public Guid TripBookingId { get; set; }

    public Guid TripId { get; set; }

    public Guid StudentId { get; set; }

    public Guid ParentId { get; set; }

    public DateTime BookingDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual Trip Trip { get; set; }
}