// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class TripSchedule
{
    public Guid TripScheduleId { get; set; }

    public Guid TripId { get; set; }

    public Guid ScheduleTypeID { get; set; }

    public DateTime? TripDate { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool RunsOnMonday { get; set; }

    public bool RunsOnTuesday { get; set; }

    public bool RunsOnWednesday { get; set; }

    public bool RunsOnThursday { get; set; }

    public bool RunsOnFriday { get; set; }

    public bool RunsOnSaturday { get; set; }

    public bool RunsOnSunday { get; set; }

    public virtual Trip Trip { get; set; }
}