// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class vw_ClinicDashboard_Metric
{
    public int? CurrentlySickStudents { get; set; }

    public int? ExpiringSoonMedications { get; set; }

    public int? LowStockMedications { get; set; }

    public int? VisitsLast30Days { get; set; }
}