// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class vw_CompletedLessonsPerStudent
{
    public Guid StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string StudentNumber { get; set; }

    public int? TotalCompletedLessons { get; set; }
}