// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class vw_PerformantTeacherSubject
{
    public Guid TeacherSubjectID { get; set; }

    public Guid TeacherID { get; set; }

    public Guid SubjectID { get; set; }

    public string TeacherName { get; set; }

    public string SubjectName { get; set; }
}