// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class vw_StudentPerformance
{
    public Guid? StudentID { get; set; }

    public string UserID { get; set; }

    public Guid? ParentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? Year { get; set; }

    public int? Month { get; set; }

    public decimal? AverageMonthlyScore { get; set; }

    public decimal PreviousAverage { get; set; }

    public int IsImproving { get; set; }
}