// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.Models;

public partial class vw_StudentAttendanceSummary
{
    public Guid StudentClassScheduleID { get; set; }

    public Guid? StudentID { get; set; }

    public Guid? ScheduleID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string DayName { get; set; }

    public Guid ReportCardID { get; set; }

    public string Term { get; set; }

    public decimal? GPA { get; set; }

    public DateTime? IssuedDate { get; set; }

    public DateTime? TermStartDate { get; set; }

    public DateTime? TermEndDate { get; set; }

    public int? AcademicLevel { get; set; }

    public int? AttendanceCount { get; set; }
}