// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.ChatModels;

public partial class ChatGroup
{
    public Guid GroupID { get; set; }

    public string GroupName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();
}