// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.ChatModels;

public partial class ChatMessage
{
    public Guid Id { get; set; }

    public string UserId { get; set; }

    public string GroupName { get; set; }

    public string Message { get; set; }

    public DateTime? Timestamp { get; set; }

    public string ReciepientId { get; set; }

    public string GroupIdentifier { get; set; }

    /// <summary>Blob path, not a public URL — a read SAS is minted per request so links cannot be
    /// shared outside the app.</summary>
    public string AttachmentPath { get; set; }

    public string AttachmentName { get; set; }

    public string AttachmentContentType { get; set; }

    public long? AttachmentSizeBytes { get; set; }

    /// <summary>Stamped once an unread-message email has gone out, so a restart cannot re-notify
    /// the same backlog. Null means never notified.</summary>
    public DateTime? NotifiedAt { get; set; }
}