// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDUSphereSharedProject.ChatModels;

public partial class GroupMember
{
    public string GroupName { get; set; }

    public string UserId { get; set; }

    public virtual ChatGroup GroupNameNavigation { get; set; }
}