// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EduSphereDomain.Models;
using EDUSphereSharedProject.FinanceModels;
using Microsoft.EntityFrameworkCore;

namespace EduSphereDomain.FinanceData;

public partial class PhoenixEdusphereFinanceContext : DbContext
{
    public PhoenixEdusphereFinanceContext(DbContextOptions<PhoenixEdusphereFinanceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<StudentFinance> StudentFinances { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.ToTable("Invoice", "Finance");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DueDate).HasColumnType("date");
            entity.Property(e => e.IssuedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PaidAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("('Pending')");
            entity.Property(e => e.TermEndDate).HasColumnType("date");
            entity.Property(e => e.TermStartDate).HasColumnType("date");

            entity.HasOne(d => d.StudentFinance).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.StudentFinanceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Invoice_StudentFinance");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.ToTable("Payment", "Finance", tb =>
                {
                    tb.HasTrigger("TR_Payment_PreventOverpayment");
                    tb.HasTrigger("TR_Payment_UpdateInvoice");
                });

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.AmountPaid).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PaymentDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("('Cash')");

            entity.HasOne(d => d.Invoice).WithMany(p => p.Payments)
                .HasForeignKey(d => d.InvoiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payment_Invoice");
        });

        modelBuilder.Entity<StudentFinance>(entity =>
        {
            entity.ToTable("StudentFinance", "Finance");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.OutstandingAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Scholarships).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("('Active')");
            entity.Property(e => e.TotalFees).HasColumnType("decimal(18, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}