// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EduSphereDomain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace EduSphereDomain.AchievementData
{
    public partial class AchievementContext
    {
        private IAchievementContextProcedures _procedures;

        public virtual IAchievementContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AchievementContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAchievementContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetUserBadgesByUserIDResult>().HasNoKey().ToView(null);
        }
    }

    public partial class AchievementContextProcedures : IAchievementContextProcedures
    {
        private readonly AchievementContext _context;

        public AchievementContextProcedures(AchievementContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetUserBadgesByUserIDResult>> GetUserBadgesByUserIDAsync(string UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserID",
                    Size = -1,
                    Value = UserID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetUserBadgesByUserIDResult>("EXEC @returnValue = [dbo].[GetUserBadgesByUserID] @UserID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
