// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EduSphereDomain.Models;
using EDUSphereSharedProject.ChatModels;
using Microsoft.EntityFrameworkCore;

namespace EduSphereDomain.MessagingData;

public partial class MessagingContext : DbContext
{
    public MessagingContext(DbContextOptions<MessagingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<ChatGroup> ChatGroups { get; set; }

    public virtual DbSet<ChatMessage> ChatMessages { get; set; }

    public virtual DbSet<GroupMember> GroupMembers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.AccountActive)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);
            entity.Property(e => e.isFirstLogin)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");
            entity.Property(e => e.requiresPasswordReset)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");
        });

        modelBuilder.Entity<ChatGroup>(entity =>
        {
            entity.HasKey(e => e.GroupID).HasName("PK__tmp_ms_x__149AF30A622092C5");

            entity.Property(e => e.GroupID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.GroupName).HasMaxLength(255);
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ChatMess__3214EC07EAD34E62");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.GroupIdentifier)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.GroupName).HasMaxLength(255);
            entity.Property(e => e.ReciepientId).HasMaxLength(255);
            entity.Property(e => e.Timestamp).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasMaxLength(255);
        });

        modelBuilder.Entity<GroupMember>(entity =>
        {
            entity.Property(e => e.GroupMemberID).ValueGeneratedNever();
            entity.Property(e => e.DateAdded).HasColumnType("datetime");
            entity.Property(e => e.GroupName).HasMaxLength(255);
            entity.Property(e => e.UserId).HasMaxLength(255);

            entity.HasOne(d => d.Group).WithMany(p => p.GroupMembers)
                .HasForeignKey(d => d.GroupID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_GroupMembers_ChatGroups");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}